### ISSUE TITLE
Should the note about restricted productions include expressionless 'yield'?

### ISSUE THREAD

**Issue by DanielRosenwasser** [tc39/ecma262#1192]
In https://tc39.github.io/ecma262/#sec-rules-of-automatic-semicolon-insertion, the noted restricted productions are not complete, but notice that

> *ReturnExpression*
> &nbsp;&nbsp;&nbsp;&nbsp;`return;`

is documented, but not

> *YieldExpression*
> &nbsp;&nbsp;&nbsp;&nbsp;`yield`

I believe the idea is just to illustrate the two possible conditions where an expression may or may not be present, so I *think* `yield` should be documented the same.

![image](https://user-images.githubusercontent.com/972891/39899769-a91f8a42-5472-11e8-8664-0c9b69296a07.png)

**Comment by littledan** [comment]
@DanielRosenwasser I agree that we should document it similarly. PRs are welcome. cc @bmeck

**Comment by bmeck** [comment]
Yes we should probably document this.

**Comment by allenwb** [comment]
I'm less sure.

The origin of this text dates all the way back to ES1 when there were only three restricted productions in the language.  In that context it probably made sense to list them there.  But now that the list is long and growing, it's less clear that a redundant list makes sense.  Redundant non-normative lists have perennially had the problem of getting out of date. Yet people tend to read them as if they are complete and normative.

My suggestion is that instead of trying to list all of the restricted production,  to either delete the entire note, or to change it  into providing a clarifying example of a single restricted production.

**Comment by bterlson** [comment]
I think we can keep this up to date personally. Since the grammar annex is auto-generated, it's a simple ctrl+F for restricted productions :)
