### ISSUE TITLE
Why forEach callback's this is window? 

### ISSUE THREAD

**Issue by BlackHole1** [tc39/ecma262#1213]
```javascrip
[1,2,3].forEach(function () {
  console.log(this)
}) //=> window x 3
```

Whether the second parameters are `empty` or `null` or `undefined`, the `this` result is `window`.

I don't think it's wise. I think it should be like this:

```javascript
[1,2,3].forEach(function () {
  console.log(this)
}) //=> Array(3) [1, 2, 3] x 3
```

Here's my Polyfill:

```javascript
Array.prototype.forEach = function (callback, thisArg) {
  var callbackSelf, thisObj, i = 0, len

  if (this == null) {
    return new TypeError('this not defined')
  }
  if (typeof callback !== 'function') {
    return new TypeError(callback + 'is not function')
  }

  thisObj = Object(this)
  callbackSelf = thisArg || thisObj
  len = thisObj.length >>> 0

  while (i < len) {
    if (i in thisObj) {
      callback.call(callbackSelf, thisObj[i], i, thisObj)
    }
    i++
  }
}
```

**Comment by claudepache** [comment]
> I don't think it's wise.

Neither do I, but it is what you get when a function is called without this-value, and `forEach` is not different from other methods that existed since the dawn of JavaScript.

If you want a wiser behaviour, use strict mode: you’ll get `undefined` (or `null`).

(And if you want a reference to the array, use the third parameter of the callback.)
