### ISSUE TITLE
`spread` is mistakenly called "an operator" in the introduction section of ES2018

### ISSUE THREAD

**Issue by zerkms** [tc39/ecma262#1295]
> It also includes rest parameter and **spread operator** support for object properties.

(highlight is mine) https://www.ecma-international.org/ecma-262/9.0/index.html#sec-intro 

Syntactically it's not an operator, so I think the wording should be changed to "spread syntax" or something like that.

**Comment by fkling** [comment]
Since this is specific to objects, maybe it should be "rest properties" and "spread properties" or "object rest" and "object spread".

Both "rest parameter" and "spread operator" are confusing at best and plain wrong at worst in the context of objects (what is a parameter in the context of objects??).

The terminology used in the spec, even in non-normative sections, should be as precise as possible IMO.
