### ISSUE TITLE
for var expression bindings and lexical declarations

### ISSUE THREAD

**Issue by leobalter** [tc39/ecma262#1365]
I'd like to clarify something I've been reading from the specs, and verify if there is any action necessary.

for productions like `for ( var f in [] ) { ... }` and `for (var f; ; ) { ... }` we have the f binding name added to VarDeclaredNames of the for Statement. This happens from Static Semantics.

If it's a BlockStatement, we might encounter the Early SyntaxError when a lexical declared name also occurs in the VarDeclaredNames of the respective StatementList. Basically: `{ let f; var f; }`.

Considering in the examples above for `for`, where bindings are appended to VarDeclaredNames, should this error also be observed?

Currently no engine observes the SyntaxError for cases like: `for (var f in []) { let f; }` and `for (var f; ; ) { let f }`.

So the possible solutions are:

1. Am I missing any text in the spec saying this SyntaxError won't happen to names appended to VarDeclaredNames?
2. We enforce the SyntaxError to be consistent and throw a SyntaxError also for names added to VarDeclaredNames and then redeclared as lexical names in the respective statement list? We add tests and expect all engines to fix this?
3. We might add a text saying the Early Error doesn't observe names appended to the respective VarDeclaredNames from extensive productions. All browsers already comply to this behavior.

Thanks

**Comment by bakkot** [comment]
> Considering in the examples above for for, where bindings are appended to VarDeclaredNames, should this error also be observed?

If I'm reading the spec correctly, the [error](https://tc39.github.io/ecma262/#sec-block-static-semantics-early-errors) refers to "the `VarDeclaredNames` of `StatementList`", whereas the [static semantics](https://tc39.github.io/ecma262/#sec-for-in-and-for-of-statements-static-semantics-vardeclarednames) `VarDeclaredNames` for `for-in` only puts the declaration in the `VarDeclaredNames` of the `for-in` statement itself. So it wouldn't be an error.

Just in case it's the source of the confusion: Lists in the spec are effectively copied rather than being mutated when they're passed between abstract operations. That is, when 13.7.5.7 says "Append to `names` the elements of the `VarDeclaredNames` of `Statement`" it doesn't actually modify the `VarDeclaredNames` of `Statement`; rather, it creates a _new_ list which is the concatenation of `names` and the `VarDeclaredNames` of `Statement`. So the `VarDeclaredNames` of the block does not start containing the names introduced by the `for` statement.

**Comment by leobalter** [comment]
Thank you so much for the clarification! This is what I was looking for and
helped my sanity while reading the specs alone.

**Comment by jmdyck** [comment]
@bakkot:
> Lists in the spec are effectively copied rather than being mutated when they're passed between abstract operations.

Hm. My first guess would be that there aren't any cases where it actually makes a difference. But if there *are* such cases, I would *not* expect copy-on-pass. See [Algorithm Conventions](https://tc39.github.io/ecma262/#sec-algorithm-conventions): aliases are reference-like, and if you don't want that, explicitly make a copy. (It's not talking about parameters specifically, but I'd expect them to behave the same as "let" aliases.)

> That is, when 13.7.5.7 says "Append to `names` the elements of the `VarDeclaredNames` of `Statement`" it doesn't actually modify the VarDeclaredNames of Statement;

True, but there shouldn't really be any question of that.

> rather, it creates a new list which is the concatenation of names and the `VarDeclaredNames` of `Statement`.

No, the List that `names` refers to is modified (by appending the elements of the `VarDeclaredNames` of `Statement`).

> So the VarDeclaredNames of the block does not start containing the names introduced by the for statement.

I have a feeling you've misread the spec. Note that it says:
```Append to _names_ the elements of X.```
and not:
```Append _names_ to the elements of X.```

(The things you're saying would be appropriate if it said the latter, but not when it says the former.)

**Comment by leobalter** [comment]
@bakkot One thing that I got from @jugglinmike in a private chat the fact I'm not looking at the actual `VarDeclaredNames of StatementList`. The spec text gives an idea it's only observed the semantics for that very production from StatementList, limiting anything added otherwise.

```
Block, Static Semantics: Early Errors
   - It is a Syntax Error if any element of the LexicallyDeclaredNames of
  StatementList also occurs in the VarDeclaredNames of StatementList.
```

**Comment by leobalter** [comment]
I got an interesting example were the append happens as well:

```js
{ let f; { var f; } }
```

The VarDeclaredNames list of the outer block contains the items from the VarDeclaredNames list of the inner block. These items are appended.

If some for-var will append names to the block, it sounds the idea is to have lexical names conflicting with the vars anyway. In anyway, `for (var f;;) { let f; }` should not be allowed from parsing. Question is: is it worth the hassle? My only reasoning is consistency.

**Comment by ajklein** [comment]
@leobalter I'm not sure I'm following you properly. But I'd like to understand the confusion. Taking the two examples from your most recent message:

1. `{ let f; { var f; } }` is indeed an error due to the appending, and the early error link @bakkot linked to. And leaving the spec language aside, it's conceptually an error since it would need to "hoist" the var over the let.
1. `for (var f;;) { let f; }` doesn't look to me like an error, conceptually: the let binding is contained to the block, so "cleanly" shadows the var binding, and the var is visible outside the block as expected (it doesn't have to be hoisted over anything. As for the spec, I don't see why it _should_ be an error; the rule about not mixing lexical and var-declared names is specific to Block. If you think the spec does say this should be disallowed, can you link to the specific section you think is responsible for generating this error?
