### ISSUE TITLE
Consider Date.setTimezone()

### ISSUE THREAD

**Issue by zoonman** [tc39/ecma262#1388]
At this moment of time there is no good way to set current timezone or timezone offset.

As result people come up with crumpled solutions like this:

```
utcDate = new Date(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate(), date.getUTCHours(), date.getUTCMinutes(), date.getUTCSeconds())
```

Also it gets incredible tricky to work with dates which has to be translated into proper timezones in future or past days when daylight saving time is used and you have to deal with multiple countries and internationalization.

**Comment by annevk** [comment]
This is not the place to make proposals per https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md. https://github.com/tc39/proposal-temporal might be of interest.

**Comment by anba** [comment]
`utcDate = new Date(date.getTime())` is shorter (and less error-prone for years in [0,99]). Or alternatively `utcDate = new Date(date.getTime() - date.getUTCMilliseconds())` if the omission of milliseconds was intentional.

Apart from that the [Temporal](https://github.com/tc39/proposal-temporal) proposal should cover most needs to work with non-default time zones.

**Comment by ljharb** [comment]
Thanks for your thoughts! The pointers to CONTRIBUTING.md and the Temporal proposal should address this :-)
