### ISSUE TITLE
Missing entry in 15.2.1.13 Static Semantics: VarDeclaredNames

### ISSUE THREAD

**Issue by pvdz** [tc39/ecma262#1538]
**Description:** 

Seems to me like `15.2.1.13 Static Semantics: VarDeclaredNames` is missing an entry for

```
ModuleItem: StatementListItem
```

(It does appear in `15.2.1.12 Static Semantics: LexicallyScopedDeclarations`)

**Comment by jmdyck** [comment]
`ModuleItem: StatementListItem` is what [5.1.1 Context-Free Grammars](https://tc39.github.io/ecma262/#sec-context-free-grammars) calls a "chain production". And so, according to [5.2.2 Syntax-Directed Operations](https://tc39.github.io/ecma262/#sec-algorithm-conventions-syntax-directed-operations), there's an implicit definition for VarDeclaredNames that looks like this:
```
    ModuleItem: StatementListItem
        1. Return VarDeclaredNames of StatementListItem.
```

> (It does appear in 15.2.1.12 Static Semantics: LexicallyScopedDeclarations)

I think you mean [15.2.1.11 Static Semantics: LexicallyDeclaredNames](https://tc39.github.io/ecma262/#sec-module-semantics-static-semantics-lexicallydeclarednames), which has:
```
     ModuleItem: StatementListItem
      1. Return LexicallyDeclaredNames of StatementListItem. 
```
which is exactly what the chain production rule would provide, and so is technically unnecesary. I think it might be there explicitly so that Note 2 has something to talk about.

**Comment by pvdz** [comment]
I see. Thanks for the clarification
