### ISSUE TITLE
AsyncGeneratorFunctionCreate: "generator" or "async generator"?

### ISSUE THREAD

**Issue by jmdyck** [tc39/ecma262#1544]
In [AsyncGeneratorFunctionCreate](https://tc39.github.io/ecma262/#sec-asyncgeneratorfunctioncreate), in the call to `FunctionAllocate`, the argument passed to the `_functionKind_` parameter is `"generator"`.

Should that be `"async generator"`?

**Comment by ljharb** [comment]
cc @domenic

**Comment by domenic** [comment]
I guess that might be good, although it appears unobservable, since the only thing the spec cares about for [[FunctionKind]] is whether it's "classConstructor" or not (in https://tc39.github.io/ecma262/#sec-ecmascript-function-objects-call-thisargument-argumentslist).

It might be simpler to just change it to a boolean.

**Comment by jmdyck** [comment]
Interesting. Originally, `[[FunctionKind]]` had three possible values (normal, generator, and classConstructor), and they had observably distinct behavior. But then bddde23 removed the step that distinguished "generator" from "normal". So at that point, it could have collapsed to a boolean. But it didn't, and instead got "async" (in 4278a8e) and then "async generator" (in b564aa94).

I think I'll take a stab at collapsing it to a boolean.
