### ISSUE TITLE
classes more open and dynamic class['']

### ISSUE THREAD

**Issue by djmisterjon** [tc39/ecma262#1550]
It would be nice to see ability to search a class

example
if i want create a new instance from a class, i need use a manual register.
this is boring and need registering manually in some context.
```javascript
         const nextScene = new (getClass('Scene_Map24'))(para); // new dynamic class
         function getClass(name) {
             switch (name) {
                 case'Scene_Boot' :return Scene_Boot ;break;
                 case'Scene_Map1' :return Scene_Map1 ;break;
                 case'Scene_Map2' :return Scene_Map2 ;break;
                 case'Scene_Map3' :return Scene_Map3 ;break;
                 case'Scene_Map4' :return Scene_Map4 ;break;
                 case'Scene_Map5' :return Scene_Map5 ;break;
                 //.....=>>>>
                 case'Scene_Map34':return Scene_Map34;break;
             }
         }
```
instead maybe a native way to do something like this ?
```javascript
         const nextScene = new class['Scene_Map24'];
         const nextScene = new class.list['Scene_Map24'];
         const nextScene = new classFrom['Scene_Map24']; // a native dom register
```

what do you think about this guys ?
It possible to add more native feature to class ?

**Comment by nicolo-ribaudo** [comment]
This repo is not for new feature proposals: I suggest reading https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#new-feature-proposals

Apart from that, I think that this proposal would receive a strong pushback, since it will make it impossible to garbage collect classes or to three-shake them. Also, it would bring a big security flaw, because it provides a way of "hacking" current JavaScript semantics by allowing access to bindings that can currently be hidden using closures.

Wouldn't this work for you?
```js
const Scenes = {
  Boot: class {},
  Map1: class {},
  // ...
};

function getClass(name) {
  return Scenes[name];
}

new (getClass(name))(params);
```
