### ISSUE TITLE
New for loop without ';' colons

### ISSUE THREAD

**Issue by ShadyGaDa** [tc39/ecma262#1553]
for loops are difficult to convert with colons to ecma6.

A normal loop.

```
for (var i=1; i<colons.length; i++) {
    colons[i] = i
}
```

A new loop.

```
for (1, <colons.length, ++) {
    colons[this]
}
```

Removal of var.
Replace colon with comma.
Simplification of process!

**Comment by ljharb** [comment]
what happens with a nested loop?

either way, please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal for how to best suggest new features for the language.

**Comment by ShadyGaDa** [comment]
I would re-consider this game changing idea.
I know there are many changes being thrown around.
The language concept is unique and original.
I am sure someone will consider and at least offer some positive criticism.
Nested loop can be worked around.

**Comment by tabatkins** [comment]
New syntax has to meet a high bar to be included. Just being shorter isn't enough: it has to be high-value (making a long or difficult-to-write-correctly thing much easier to write); it has to mesh well with existing syntax; and it generally needs to allow a fairly unique new capability that would be useful for a reasonable fraction of programs.

This proposal unfortunately fails all of these criteria. For loops *are* hard to write (often very difficult for beginners to read and write), but this doesn't significantly change that, it just makes it slightly shorter. It doesn't mesh well with existing syntax, as it assumes a *very particular* (tho common) for-loop structure, and invents a new "skip the variable name" syntax variant that's not used anywhere else; nor is this variant compatible with any other pattern, like calling a boolean function for the test portion rather than just inlining a comparison. It also stomps on the already-confusing `this` keyword, with no way to declare a different variable name, which means you can't nest it easily, or use it in a method. And finally, it offers zero new capabilities; it's just a slightly shorter for loop.

So, this proposal unfortunately fails all the criteria for adding new syntax to JS.
