### ISSUE TITLE
How should ECMA-262 be used by other specs?

### ISSUE THREAD

**Issue by jmdyck** [tc39/ecma262#1621]
Over in PR #1620, @ljharb [said](https://github.com/tc39/ecma262/pull/1620#discussion_r302749838):
> [ECMA-262's] abstract operations are not a utility library [for other specs]

[Editorial insertions are mine. @ljharb, please let me know if I have distorted your intent.]

I find this interesting. Is there anything to prevent (or even just discourage) other specs from treating 262's abstract operations that way? More generally, are there any guidelines for how other specs are supposed to make use of 262? If not, should there be?

**Comment by ljharb** [comment]
It's always great when HTML or Intl (or other layered specs that probably exist that I'm unaware of) can find ways to utilize operations in 262 - but I'd think that when they differ from their intended usage, that we'd want to *know* about them so that in the future we could avoid breaking them unintentionally.

As to my intent with that comment; i didn't really mean "for other specs" as much as I meant that abstract operations don't exist for general potential of reuse like utility libraries do; they exist for the specific potential of reuse inside 262, and with known layering points for external specs (ie, HTML or Intl).

**Comment by jmdyck** [comment]
>  and with known layering points for external specs (ie, HTML or Intl).

But we don't really declare what those points are, do we?

**Comment by ljharb** [comment]
Not explicitly, i believe, barring a few host hooks and host-dependent algorithms.

**Comment by ljharb** [comment]
This seems answered? Happy to reopen if not.
