### ISSUE TITLE
AssignmentTargetType can be changed back to IsValidSimpleAssignmentTarget

### ISSUE THREAD

**Issue by anba** [tc39/ecma262#1643]
#1132 changed IsValidSimpleAssignmentTarget to AssignmentTargetType to be able to differentiate between ReferenceError and SyntaxErrors when assigning to `eval`/`arguments` in strict-mode. But with #1527 fixed, this change is no longer necessary and AssignmentTargetType can be changed back IsValidSimpleAssignmentTarget. 

-----

AssignmentTargetType returns either `simple`, `invalid`, or `strict`, but since #1527 we only need to differentiate between `simple` and not-`simple`, so a boolean is sufficient, which was exactly the return type of IsValidSimpleAssignmentTarget.

**Comment by ljharb** [comment]
It seems prudent to me to prefer an extensible enum to an implicit boolean.

**Comment by rkirsling** [comment]
Enum or not though, it certainly doesn't seem meaningful to keep a separate value for [12.1.3](https://tc39.es/ecma262/#sec-identifiers-static-semantics-assignmenttargettype) anymore.

**Comment by ljharb** [comment]
Agreed there.

**Comment by claudepache** [comment]
In expression like `[a, b] = [1, 2]`, it is strange that AssignmentTargetType of that production is “invalid”, since this expression is a perfectly valid destructuring assignment. The “strict” value makes even less sense.

So, it is more readable either to revert to IsValidSimpleAssignmentTarget, or to rename the “invalid” and “strict” states into “nonsimple”.

Alternatively, we could have the three following states: “simple”, “destructuring”, “invalid”.

**Comment by rkirsling** [comment]
That's an excellent point. If there are only two meaningful states now, and if "invalid" already really means "non-simple", and if `nonsimple` is kind of a weird enum value, then I would vote for reverting to boolean.

**Comment by zenparsing** [comment]
But the assignment expression `[a, b] = [1, 2]` is not in fact a valid assignment **target**; isn't it confusing to call it "non-simple"? In what "non-simple" context could you use that as an assignment target?

**Comment by rkirsling** [comment]
@zenparsing Hmm, that's also true. Should we just change `strict` to `invalid` and call it a day then?

**Comment by claudepache** [comment]
[Currently in spec (12.15.1)](https://tc39.es/ecma262/#sec-assignment-operators-static-semantics-early-errors):

![Capture d’écran 2019-08-02 à 19 50 07](https://user-images.githubusercontent.com/3309637/62388907-ca792100-b55e-11e9-8a3a-413b71c4339d.png)

(Ditto in [12.5.5.1](https://tc39.es/ecma262/#sec-destructuring-assignment-static-semantics-early-errors), etc.)

I think it makes sense to define three possible values for AssignmentTargetType,  namely “simple”, “destructuring” and “invalid”, so that the early error condition may be replaced with:

* It is an early Syntax Error if _LeftHandSideExpression_ is neither destructuring nor simple.

**Comment by leobalter** [comment]
> In expression like [a, b] = [1, 2], it is strange that AssignmentTargetType of that production is “invalid”

@claudepache where is it invalid?

**Comment by claudepache** [comment]
> > In expression like `[a, b] = [1, 2]`, it is strange that AssignmentTargetType of that production is “invalid”
> 
> @claudepache where is it invalid?

I meant: AssignmentTargetType of `[a, b]` (gonna clarify my comment). See [12.2.1.5](https://tc39.es/ecma262/#sec-semantics-static-semantics-assignmenttargettype)

**Comment by leobalter** [comment]
I prefer the original text with the two distinct items. The ArrayLiteral might not be necessarily covering an AssignmentPattern. e.g `[x++]`. This would require keeping `AssignmentTargetType (ArrayLiteral)` returning `destructuring` if it's an `AssignmentPattern` or `invalid` if not. 

At the end, we would just move the condition, right?

**Comment by rkirsling** [comment]
One way or another, at this moment, there is exactly one bit of information that we care about here, so adding additional values doesn't help anyone—it's literally the opposite of this issue's stated goal.

The `true` case here is easy to put into words, as we can certainly say when something is a "simple assignment target". The `false` case is harder to express, and I think this difficulty is exacerbated by the existing enum being called "type", which makes it sound like we're aiming to be more specific than we actually are.  Indeed, we'd run into the same problem if we renamed `IsFunctionDefinition` to `FunctionDefinitionType`, `IsSimpleParameterList` to `ParameterListType`, etc. And it's not like renaming the enum makes the problem go away—even if we called it `AssignmentTargetSimplicity`, what would the values be?

Honestly, this is precisely what booleans are good for—by sticking to an enum when it's not called for, we basically just end up fighting over the best way to verbalize `true` and `false`. 😐

**Comment by ljharb** [comment]
While I agree with that, I'm convinced that at some point in the future, if we refactor this back to a boolean, we'll have to have *yet another* conversion and bikeshed back to an enum.

**Comment by jmdyck** [comment]
> In expression like `[a, b] = [1, 2]`, it is strange that AssignmentTargetType of `[a, b]` is “invalid”, since this expression is a perfectly valid destructuring assignment.

In that expression, the LeftHandSideExpression is an ArrayLiteral, so the first rule of [12.15.1](https://tc39.es/ecma262/#sec-assignment-operators-static-semantics-early-errors) applies, and the second rule doesn't, so AssignmentTargetType won't be invoked on `[a, b]`. So the AssignmentTargetType of `[a, b]` is not relevant in that expression.

There are *other* expressions for which it's relevant, e.g. `([a, b]) = [1,2]`, but then the fact that it's 'invalid' isn't strange, because that isn't a valid destructuring assignment.

> Alternatively, we could have the three following states: “simple”, “destructuring”, “invalid”.

There wouldn't be any reason to use "destructuring".

**Comment by jmdyck** [comment]
> The ArrayLiteral might not be necessarily covering an AssignmentPattern. e.g `[x++]`. This would require keeping `AssignmentTargetType (ArrayLiteral)` returning `destructuring` if it's an `AssignmentPattern` or `invalid` if not.

In an expression like `[x++] = [1]`, where the LeftHandSideExpression is an ArrayLiteral, AssignmentTargetType isn't invoked. So AssignmentTargetType doesn't care whether an ArrayLiteral covers an AssignmentPattern.

**Comment by rkirsling** [comment]
@ljharb Just to clarify your concern a step more deeply: Are you expecting that the functionality that might be desired in the future would be specifically that of a more detailed assignment target _type_ enumeration (i.e., that we wouldn't also want to update the enum name at that time)?

I can understand wanting to avoid needless churn if we're accumulating `oldids` every time—in fact, this is a good argument for literally reverting to `IsValidSimpleAssignmentTarget` instead of trying to rename it too—but I don't think A→B→A→C is necessarily more harmful than A→B→C...right?

**Comment by ljharb** [comment]
In general, I find that using booleans works only and until there's a third option - at which point, it's best to never go back to the boolean.

In general, 4 steps is more harmful than 3 steps because it's more churn in the spec.

**Comment by jmdyck** [comment]
@claudepache:
> I think it makes sense to define three possible values for AssignmentTargetType, namely “simple”, “destructuring” and “invalid”, so that the early error condition may be replaced with:
> 
>     * It is an early Syntax Error if _LeftHandSideExpression_ is neither destructuring nor simple.

(Presumably you mean "... if **AssignmentTargetType** of LeftHandSideExpression is neither ...".)

So then, you would need AssignmentTargetType to return 'destructuring' in those cases when LeftHandSideExpression is either an ObjectLiteral or an ArrayLiteral and is also covering an AssignmentPattern. But that would be a bit tricky. E.g., what is the AssignmentTargetType of `[a]`?
* In `[a] = [1]`, you'd need it to return 'destructuring`, but
* in `([a]) = [1]`, you'd need it to return 'invalid'.

**Comment by claudepache** [comment]
> (Presumably you mean "... if **AssignmentTargetType** of LeftHandSideExpression is neither ...".)

(Indeed, I’ll correct my comment.)


> So then, you would need AssignmentTargetType to return 'destructuring' in those cases when LeftHandSideExpression is either an ObjectLiteral or an ArrayLiteral and is also covering an AssignmentPattern. But that would be a bit tricky. E.g., what is the AssignmentTargetType of `[a]`?
> 
> * In `[a] = [1]`, you'd need it to return 'destructuring`, but
> * in `([a]) = [1]`, you'd need it to return 'invalid'.

I don’t see it especially tricky. Unless I miss something obvious, you just need to redefined AssignmentTargetType for those two sets of productions:

```
    PrimaryExpression :
        ObjectLiteral
        ArrayLiteral
```

Instead of ~~Return “invalid”~~:
1. If _PrimaryExpression_ is covering an _AssignmentPattern_, return “destructuring”.
2. Return “invalid”.

```
     ParenthesizedExpression : ( Expression ) 
```

Instead of ~~Return AssignmentTargetType of _Expression_~~:
1. If AssignmentTargetType of _Expression_ is “simple”, return “simple”.
2. Return “invalid”.

(At this point, I could just write the PR, since it is effectively... simple. I expect to do that today and let you decide.)

**Comment by jmdyck** [comment]
Yup, I think that would work. (And I think I prefer it to the status quo, though I'm not positive.)

**Comment by claudepache** [comment]
> (At this point, I could just write the PR, since it is effectively... simple. I expect to do that today and let you decide.)

While working on that PR, the following question arose:

In [12.5.1](https://tc39.es/ecma262/#sec-assignment-operators-static-semantics-early-errors), there are two Early Error rules for:

    AssignmentExpression : LeftHandSideExpression = AssignmentExpression

But when `LeftHandSideExpression` is covering an [`AssignmentPattern`](https://tc39.es/ecma262/#prod-AssignmentPattern), for example:

    [ this ] = [ ]

it is not clear from reading the spec that [the Early Error rules of `AssignmentPattern`](https://tc39.es/ecma262/#sec-destructuring-assignment-static-semantics-early-errors) have also to be applied (although, of course, notwithstanding bugs in the spec, they must be applied).

By contrast, in [13.7.5.1](https://tc39.es/ecma262/#sec-for-in-and-for-of-statements-static-semantics-early-errors), it is explicitly stated that “the Early Error rules for AssignmentPattern are used.”

What do you think? Is there an oversight here?

**Comment by jmdyck** [comment]
Looks like an oversight to me.

((
I think the general rule is that if X is covering a Y, then
(a) you don't apply the Early Error rules for X ("and its derived productions"), and
(b) you do apply the Early Error rules for Y ("and its derived productions").

The spec usually says (b) (with omissions in 12.15.1 and 12.15.5.1), but it often doesn't say (a), and I'm not yet sure whether that's because:
- you actually *are* supposed to apply the rules for X (etc) too, or
- it doesn't matter, either because there aren't any rules for X (etc) or because any errors you'd find under X will also be found under Y, or
- it does matter, and it's another spec oversight.

))

**Comment by claudepache** [comment]
I’ve opened PR #1658 for the two missing early error rules from the covered AssignmentPattern.

Also, I withdraw my suggestion to add a “destructuring” value for AssignmentTargetType, as it does not really simplify or clarify the early error rules.
