### ISSUE TITLE
Some Notes should be presented as a part of specification

### ISSUE THREAD

**Issue by ToshiKurokawa** [tc39/ecma262#176]
[JP22] This is not a factual issue but a meta issue for the style of standard document: 
Many contents of the NOTE for the Language seems to be specifications expressed in English rather than just an informative note. I’ve got that from notes in 13.3.2.4, 13.7.5.9, 13.10, 13.11. It looks that a subclause entitled “Summary” might be useful to guide the readers of this document.

**Comment by bterlson** [comment]
> Many contents of the NOTE for the Language seems to be specifications expressed in English rather than just an informative note.

@ToshiKurokawa In general, notes will frequently restate what the specification text says for a specific case especially when that case has a history of being misinterpreted. I believe the rationale here is for these to be notes so we don't create any doubt about what the normative requirements actually are, and to avoid bugs cropping up in implementations due to a conflict in normative semantics that are potentially spread out around the spec.

Changing this convention at this point would require stronger motivation than what is presently given. I'm closing this for now, but please re-open if you would like to discuss further (and I will try not to miss this issue for so long next time :))
