### ISSUE TITLE
Some comments on “Table 49: The_TypedArray_Constructs”

### ISSUE THREAD

**Issue by nisiyama** [tc39/ecma262#181]
[JP22] In this table, “Description” column describes physical representation of types including their bit length, and “Equivalent C Type” column describes corresponding types in C language.  However, as far as I know, C language specification do not specify exact length of types. In addition, this table refers to “IEEE floating point”.  However, there is no pointer which “IEEE floating point specification this tables refers.

**Comment by bterlson** [comment]
@nisiyama thanks for pointing this out!

AFAIK, the equivalent C type isn't so much pointing out the exact length but instead the range of values the type accepts. The C standard defines these I believe, but a C expert could comment otherwise. In any case, the descriptions are still generally useful.

The IEEE Floating point specification is the one referred to in the bibliography (annex F), namely IEEE 754-2008.
