### ISSUE TITLE
referencing a const or let variable with this keyword is undefined

### ISSUE THREAD

**Issue by moonformeli** [tc39/ecma262#1834]
**Description:** 
I'm not sure if this is an intended feature. 
When x is called with `this` keyword, it gives you an undefined.
I've tried to find the reason for this in ecma-interantional.org but don't know where I could find it.
Could someone provide me a link I can convince myself for why this isn't a bug?

**Output:**

```
const x = 1;

console.log(this.x); // undefined
```

**Comment by ljharb** [comment]
This isn't a bug because variables aren't the same as properties (except when you're in the global scope of a Script).

**Comment by bathos** [comment]
> Could someone provide me a link I can convince myself for why this isn't a bug?

It might help to reframe the question mentally if you’re still trying to see where this does/doesn’t occur. Rather than trying to figure out why it doesn’t happen here, you may have an easier time picking through the spec to figure out why it _does_ happen under specific conditions involving `var` and `function` declared bindings in scripts or undeclared bindings in sloppy mode scripts.

Unfortunately I don’t think there’s a single key part of the spec one can point to that explains all this in depth. The behaviors arise from a number of algorithms working together. Some key bits to look at:

1. The [Reference][0] specification type
2. The related [PutValue][1] operation (esp. step 5, where a sloppy unresolvable reference can obtain the global this as the value to which a property gets assigned)
3. The [GetIdentifierReference][2] operation, which is recusrive and can bottom out with an unresolvable reference
4. The [runtime semantics][3] (eval rules) of `VariableDeclaration : BindingIdentifier Initializer[opt]`, which use GetIdentifierReference indirectly through ResolveBinding and end with a PutValue call.

TBH it’s a bit confusing (and a note in the last link seems to reference a non-existent sixth step...), so I’m not sure I’ve nailed the right/best spots to look at, but hopefully it gives you a handhold for further investigation.

[0]: https://tc39.es/ecma262/#sec-reference-specification-type
[1]: https://tc39.es/ecma262/#sec-putvalue
[2]: https://tc39.es/ecma262/#sec-getidentifierreference
[3]: https://tc39.es/ecma262/#_ref_12315

**Comment by rkirsling** [comment]
> a note in the second-to-last item’s linked op seems to reference a non-existent sixth step

Interesting, looks like the note was correct in ES2018 but became invalid in ES2019. And it's not alone. Will create a PR to fix, but this makes referring to step numbers seem like a really dangerous practice...
