### ISSUE TITLE
ECMAScript specification documentation needs to be updated about JSON.stringify(24.5.2.1)?

### ISSUE THREAD

**Issue by moonformeli** [tc39/ecma262#1840]
[This version](https://tc39.es/ecma262/#sec-json.stringify) and [this newer version](https://www.ecma-international.org/ecma-262/9.0/#sec-json.stringify) has different steps when `Type(value)` is `bigint`.

But the (relatively) older documentation seems it's not even giving me specific information, either.  
Since there's no `else` step for `b. If IsCallable(toJSON) is true, then`.
Here's the example.

```js
var a = {
  o: BigInt(1)
}

JSON.stringify(a)

/* Error */
VM1990:1 Uncaught TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at <anonymous>:1:6
```
So I wonder where this error's from and it seems the documentation needs to be updated?
Or am I missing something?
Thank you.

Plus, which documentation should I count on also? :)

**Comment by devsnek** [comment]
You should always reference https://tc39.es/ecma262. BigInt did not exist in ECMAScript 2018, so there is no reference to it in JSON.stringify.

**Comment by moonformeli** [comment]
Thank you.
Then it makes sense.
But I literally soon found this.
```js
If Type(value) is BigInt, throw a TypeError exception.
```
So why JSON.stringify should throw an error when BigInt comes in?

**Comment by devsnek** [comment]
There is no representation of BigInt in JSON, so there's no possible value for JSON.stringify to output when given a BigInt. The only reasonable behaviour is to throw.

**Comment by moonformeli** [comment]
Thank you. Problem's solved.

**Comment by allenwb** [comment]
> There is no representation of BigInt in JSON, so there's no possible value for JSON.stringify to output when given a BigInt. The only reasonable behaviour is to throw.

That's not correct the ECMA standard for [ECMA-404: The JSON Data Interchange Syntax, section 5](https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) places no limit on the number of digits in a JSON number. So a BitInt _could_ be be precisely represented in a JSIN document as a JSON number.

Furthermore ECMA-404 says:

>  [ECMA-404] also intentionally does not define how a valid JSON text might be internalized into the data structures of a programming language. There are many possible semantics that could be applied to the JSON syntax and many ways that a JSON text can be processed or mapped by a programming language. Meaningful interchange of information using JSON requires agreement among the involved parties on the specific semantics to be applied. Defining specific semantic interpretations of JSON is potentially a topic for other specifications.  

So, it would be perfectly valid according to ECMA-404 for ECMAScripts's `JSON.stringify` to serialize BitInt values as JSON numbers with full accuracy.  Since BitInt values are a distinct ECMAScript type, `JSON.stringify` could easily do that.   The problem, is that there is no backwards compatible way for JSON.parse to _automatically_ convert such "large" JSON Number values into ECMAScript BigInt values.  The problem is that the legacy definition of `JSON.parse` converts such  large JSON Numbers to ECMAScript Number values and there are undoubtably existing programs that depend upon that behavior.

But there are potential ways around this, for example, `JSON.parse`  might be augmented with an options objects that included provisions for stating that some or all JSON Numbers should be deserialized as BitInts.

There is clear utility in being able to interchange BitInt values using JSON.  For example, consider two JavaScript Workers that interchange data using a specific fixed JSON schema that is a JSON array of numeric  "64-bit" integer values.  It would be much more convenient for JSON.stringify/parse to be able to process "large" JSON Number values than it is for the application code to have to explicitly encode the values as strings prior to using `JSON.stringify` and  to explicitly decode such strings into BitInts after processing by `JSON.parse`. 

This could be accomplished by adding appropriate encoding/decoding control options  to `JSON.parse` and `JSON.stringify`.

**Comment by devsnek** [comment]
@allenwb sorry yes, I meant no *unique* representation (under the assumption you want to be able to correctly reconstruct the input data).

Sidenote: the web has "structured cloning" which I made an issue about turning into a more generalized api, but there was no implementation interest in doing so.

**Comment by moonformeli** [comment]
@allenwb 
But then I have another question.
I've reading [ECMAScript-404 pdf](https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf), it says the values that can be a JSON value are an object, array, number, string, true, false, or null. So there's no a function.

I know `JSON.stringify({a: function() {}})` doesn't contain the `a` since it has a function. But then why it doesn't give you an error, while BigInts does?
