### ISSUE TITLE
What does GetValue operation do in the void operator algorithm

### ISSUE THREAD

**Issue by dSalieri** [tc39/ecma262#1855]
There is a [void operator][1] in the specification algorithms. A note on this algorithm says:
> GetValue must be called even though its value is not used because it may have observable side-effects.

What could be the observed side-effects of running GetValue? And why do we need the second GetValue step (it just gets the data value)? Isn't the first step enough?

[1]: https://tc39.es/ecma262/#sec-void-operator

**Comment by ljharb** [comment]
```js
Object.defineProperty(window, 'foo', { get() { console.log('side effect'); } });
void foo;
```

**Comment by devsnek** [comment]
To expand on the above, member expressions and identifiers in js evaluate to an internal spec type called a reference (for example, `a.b` evaluates to `Reference { base: a, property: 'b' }`). `GetValue` unwraps this reference to the actual value, and that may involve invoking getters.

**Comment by claudepache** [comment]
(Partly overlapping the answer above, too lazy in order to trim the point already answered.)

> What could be the observed side-effects of running GetValue?

Among other things: A user-defined getter or proxy handler (with arbitrary side-effects) may be invoked. An undeclared variable in strict mode may be touched.

> And why do we need the second GetValue step (it just gets the data value)? Isn't the first step enough?

Evaluating an expression produces in some cases a [Reference], which is a spec-internal value not directly observable by user. Examples of expressions that produces a Reference are: referencing a variable, a property of an object. In general, the [GetValue] operation reads an [ECMAScript value] from that Reference (and returns a non-Reference value as-is), the [PutValue] operation write a value to that Reference.

[Reference]: https://tc39.es/ecma262/#sec-reference-specification-type
[ECMAScript value]: https://tc39.es/ecma262/#sec-ecmascript-language-types
[GetValue]: https://tc39.es/ecma262/#sec-getvalue
[PutValue]: https://tc39.es/ecma262/#sec-putvalue

**Comment by dSalieri** [comment]
@ljharb is an interesting example, are there any other examples?

---
@devsnek yes I know what the specification type Reference is. But thanks for the clarification (I would like to see even more examples, if possible).

---
@claudepache
Yes, an undeclared variable and not in strict mode will throw an error due to GetValue in void.
Also thanks for the clarifications on the type of Reference.

**Comment by ljharb** [comment]
@dSalieri inside a `with` statement.

This seems answered?

**Comment by dSalieri** [comment]
@ljharb I would like to see as many examples as possible on my question if possible. What's wrong with `with`?

**Comment by ljharb** [comment]
```js
const o = { get foo() { console.log(‘side effect’); } };
with(o) {
  void foo;
}
```

If you’re seeking further examples, the [discourse](https://es.discourse.group/) is a better place to ask than the repo for the specification.

**Comment by dSalieri** [comment]
@ljharb with `with` I get it. Only I asked for examples besides using a getter, are there such examples or is using a getter the only way to get side-effects in the void operator?

Didn't know about discourse, thanks.

**Comment by ljharb** [comment]
I'm not aware of any other mechanisms where referencing a variable has any observable effect, side or otherwise, except:
 1. `with` converting it to a property Get
 1. a global variable becoming a property Get on the global
 1. referencing an undeclared variable and generating a ReferenceError

Both of the first two would require getters, or exotic host objects.

**Comment by dSalieri** [comment]
@ljharb why did you specifically specify a global variable? Can not any other object be used besides the global one?

**Comment by devsnek** [comment]
@ljharb or proxies

**Comment by ljharb** [comment]
@dSalieri the only scopes i'm aware of where variables get translated into properties are the global scope, and `with`.

@devsnek ah yes, true, anywhere a getter kicks in, so too would a proxy handler.

**Comment by dSalieri** [comment]
@ljharb and you about it, then it is clear. Now you can close the question. Thanks to all who answered here and in particular to you ljharb
