### ISSUE TITLE
editorial nit: having both `UTF16Encode` and `UTF16Encoding` is weird

### ISSUE THREAD

**Issue by bakkot** [tc39/ecma262#1863]
Pulling this out of [#1552](https://github.com/tc39/ecma262/pull/1552#discussion_r373762709) now that it's merged:

I feel somewhat negatively about having both [`UTF16Encoding`](https://tc39.es/ecma262/#sec-utf16encoding) and [`UTF16Encode`](https://tc39.es/ecma262/#sec-utf16encode) (because the names are too similar). Unfortunately I don't have an obviously superior name to suggest. `UTF16EncodeText` instead of `UTF16Encoding`, perhaps?

**Comment by jmdyck** [comment]
To me, `UTF16EncodeText` suggests the semantics of `UTF16Encode` (i.e., it operates on _text_, a sequence of Unicode code points), so would be a confusing rename for `UTF16Encoding`.

Instead, how about renaming `UTF16Encoding` as `UTF16EncodeCodePoint` (since it operates on a single code point)?

Note that any renaming of `UTF16Encoding` will likely not be as simple as a search-and-replace, because there are uses of the form "the UTF16Encoding of <some code point>", which will sound odd we rename it from a noun (gerund) to a verb. (Mind you, invoking an abstract operation via that syntax is unusual to begin with, so it would be nice to make those more conventional.)

**Comment by bakkot** [comment]
> To me, `UTF16EncodeText` suggests the semantics of `UTF16Encode` (i.e., it operates on text, a sequence of Unicode code points), so would be a confusing rename for `UTF16Encoding`.

Sorry, I meant to suggest it as a name for `UTF16Encode`, yes.

> Instead, how about renaming `UTF16Encoding` as `UTF16EncodeCodePoint` (since it operates on a single code point)?

Works for me. I am happy with also changing the invocation style for the operation.

**Comment by domenic** [comment]
/cc @annevk who I thought had raised this before.

In general in web browser software at least, "encode" in the context of text refers to going from code points to bytes. This isn't really what is done in these operations, which go from code points to code units.

The names I would suggest are UTF16CodePointToCodeUnits and UTF16CodePointsToCodeUnits.
