### ISSUE TITLE
Error in B.3.3.6 Changes to BlockDeclarationInstantiation

### ISSUE THREAD

**Issue by johnnygerard** [tc39/ecma262#1942]
Replacement step 1.a (see below) violates 'Assert: envRec must have an uninitialized binding for N.' (step 2 of 8.1.1.1.4).

During BlockDeclarationInstantiation the following steps are performed in place of step 4.b.iii:

1. If envRec.HasBinding(fn) is false, then
        a. Perform envRec.InitializeBinding(fn, fo).

**Comment by bakkot** [comment]
Ah, yup. This was introduced in https://github.com/tc39/ecma262/pull/453 (and later modified in https://github.com/tc39/ecma262/commit/204f7935 as part of https://github.com/tc39/ecma262/pull/866).

The `If envRec.HasBinding(fn) is false` check doesn't really make sense, because all relevant bindings are already created during [BlockDeclarationInstantiation](https://tc39.es/ecma262/#sec-blockdeclarationinstantiation) 4.a. I believe it should instead be a check to see if the binding was already initialized (which there isn't an abstract operation for; we just say something like `If the binding for N in envRec is an uninitialized binding` as in [GetValue](https://tc39.es/ecma262/#sec-getvalue)).

cc @littledan and @anba in case either of you remember touching this part and can confirm.

(For context, the intention of this part of the spec is to allow

```js
{
  function f(){}
  function f(){}
}
```
which violates two invariants in the usual BlockDeclarationInstantiation algorithm: first, that each  name in the block is declared exactly once, and second, that each binding corresponding to a function declaration in the block is given a value during BlockDeclarationInstantiation exactly once. The [two tweaks in B.3.3.6](https://tc39.es/ecma262/#sec-web-compat-blockdeclarationinstantiation) are intended to be patches to allow make the algorithm correct when each of those invariants is violated respectively.)

**Comment by anba** [comment]
> cc @littledan and @anba in case either of you remember touching this part and can confirm.

Hmm, maybe that happened because I've implemented this part slightly different in [es6draft](https://github.com/anba/es6draft/blob/5487e074da2f9489fa2d8c653f037c0969bb2a68/src/main/java/com/github/anba/es6draft/compiler/BlockDeclarationInstantiationGenerator.java#L157-L177)? Anyway, the applied changes look correct to me! :-)
