### ISSUE TITLE
Promise.all: slightly inaccurate text regarding the rejection reason

### ISSUE THREAD

**Issue by marjakh** [tc39/ecma262#1983]
Text in https://tc39.es/ecma262/#sec-promise.all : 

> The all function returns a new promise which is fulfilled with an array of fulfillment values for the passed promises, or rejects with the reason of the first passed promise that rejects. 

However, if an error is thrown while we iterate the Promises, we reject the overall promise with that particular error. The error is not "the reason of the first passed promise that rejects". Though, the error can be permissively interpreted to be equivalent to rejecting the Promise we were currently iterating (if there's an non-zero amount of them).

The iteration failures occur if:
- `GetIterator` throws (Promise.all steps 3-4)
- `Iteratorstep` throws (PerformPromiseAll steps 8.a - c)
- `Call(resultCapability.[[Resolve]])` throws (PerformPromiseAll step 8.iii.2)
- `IteratorValue` throws (PerformPromiseAll steps 8.e - g)
- `Call(promiseResolve)` throws (PerformPromiseAll steps 8.i)
- `Invoke(nextPromise, "then")` throws (PerformPromiseAll step 8.r)

(Similar inaccuracies occur in Promise.race and Promise.any.)

**Comment by mathiasbynens** [comment]
Marja spotted this while implementing/reviewing the proposed `Promise.any` spec text. The tracking issue for fixing the same problem there is https://github.com/tc39/proposal-promise-any/issues/61.

**Comment by bakkot** [comment]
For in-prose descriptions of functions we generally only describe what happens if you give them valid input. Compare e.g. [`JSON.stringify`](https://tc39.es/ecma262/#sec-json.stringify), which just says it returns a String but obviously can also throw if you pass it an object with a throwing enumerable getter, or [`Promise.resolve`](https://tc39.es/ecma262/#sec-promise.resolve) which says it returns a new promise resolved with the passed argument but which can also throw if its argument is not a Promise and can return a rejected promise if its argument is an object with a  throwing `.then` getter, etc.

**Comment by marjakh** [comment]
Right. This came up with "Promise.any", where the text suggests that when it rejects, it always rejects with an AggregateError. However, that's not true. In the context of Promise combinators, this is more subtle than just an implicit "or throws". E.g., it would be almost equal to a case where the text says that a function returns a String, whereas it actually returns "false" in some error cases.

But I guess we can't do much here without being inconsistent with other parts of the spec.

**Comment by marjakh** [comment]
Closing this as this prob only makes sense to discuss in terms of Promise.any.
