### ISSUE TITLE
What's the historical reason that the specification says, about pause algorithm?

### ISSUE THREAD

**Issue by moonformeli** [tc39/ecma262#1990]
In [this specification](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#dom-alert), about `window.alert`, the step 8 is 

> Optionally, pause while waiting for the user to acknowledge the message.

And it describes `pause` as follows.

> Some of the algorithms in this specification, for historical reasons, require the user agent to pause while running a task until a condition goal is met.

But I couldn't find any references about what that historical reasons were, to hold and block the whole program until the "goal" is met.
Anyone who knows about this?

**Comment by devsnek** [comment]
Wrong repo, I think you're looking for https://github.com/whatwg/html/

**Comment by TimothyGu** [comment]
You should probably file an issue with the HTML Standard, instead of here. But the reason is that `window.alert()` needs to synchronously return after the user has acknowledged the dialog box, which you can’t do when the event loop is still running. The pause algorithm, well, pauses the event loop so that synchronous return can work.

If you have further questions, let’s continue the discussion over at https://github.com/whatwg/html.

**Comment by moonformeli** [comment]
Thank you, guys!
