### ISSUE TITLE
thinking about spec.html

### ISSUE THREAD

**Issue by codehag** [tc39/ecma262#1999]
This is just an idea...

my problem: I have a hard time knowing why some line in the spec changed. My current process is to use git blame on spec.html, search for the line, find the most recent change, checkout that commit, search for the line, repeat. 

I am having to rely a lot of git blame in order to see how / where the spec changes. I also know that people have built their own tools to track this. https://arai-a.github.io/ecma262-compare/

So, I am wondering if other people share this issue and if we should tackle this somehow. For example, splitting spec.html into chapters that can be indexed by github, so we can track the history of changes through the file. Then, we could have a build step that takes all of these files and combines them into the monster spec. 

Is this a problem for others?

**Comment by Jack-Works** [comment]
Or split them into many pages will be nice, that will improve the browsing performance on the mobile device

**Comment by ljharb** [comment]
Splitting into multiple files means we’d lose git history on the main file, unfortunately. It would, however, make it practical to build a single and multi page rendering of the spec (#1270, https://github.com/tc39/ecmarkup/issues/151)

**Comment by littledan** [comment]
I have to say, I really like how spec.html is one file. I find ECMA-402, which is split into multiple files (as ecmarkup's build step has long allowed), much more difficult to read and edit. I don't think that splitting into files would make history more clear, not just because it'd break `git blame` immediately, but also because many important changes just don't end up being factored into different files cleanly. Unfortunately, I don't have much of a suggestion for how to make reviewing spec history easier, beyond @arai-a's awesome tool.

I think we should consider the browsing experience differently from the editing one. I don't see why a single file couldn't render into multiple pages. For example, the HTML spec supports multipage builds despite being developed in a single file.

**Comment by arai-a** [comment]
what if there's an specially rendered HTML file that has a blame button (that leads us to the GitHub commit, or latest HTML with/without the text) for each line/text?
just like what [searchfox](https://searchfox.org/)'s blame column provides

**Comment by syg** [comment]
Voicing support for editing the source spec in a single file. Until such time it grows into a monstrosity that can no longer be loaded in text editors, I'd really rather not break it up.

**Comment by jasonwilliams** [comment]
> Splitting into multiple files means we’d lose git history on the main file, unfortunately. It would, however, make it practical to build a single and multi page rendering of the spec (#1270, [tc39/ecmarkup#151](https://github.com/tc39/ecmarkup/issues/151))

I would be interested in taking advantage of this to create multi-page rendering of the spec, some devices already struggle to load the whole spec as its too large.

**Comment by bakkot** [comment]
We can create a multi-page rendering of the spec without splitting `spec.html`, just as we could create a multi-page `spec.html` without splitting the rendering of the spec. Let's keep the two separate. Creating a multi-page rendering of the spec is tracked in https://github.com/tc39/ecmarkup/issues/151.

(PRs welcome for https://github.com/tc39/ecmarkup/issues/151, by the way; I'd be happy to work with anyone who wants to contribute. I'll probably get to it eventually myself, but I have higher priorities at the moment.)

**Comment by codehag** [comment]
Arai’s comment might work, we could do something like searchfox.

**Comment by rkirsling** [comment]
I strongly support the idea of a multipage `spec.html`, as this is the only repo I know of where one has to `git blame` via CLI and is prevented from doing so on github.com itself.

I'm floored to hear @littledan's opinion about ECMA-402's file splitting; it's only recently that I've been digging into that repo and I think its use of multiple spec files is role-model behavior.

**Comment by jmdyck** [comment]
> my problem: I have a hard time knowing why some line in the spec changed. My current process is to use git blame on spec.html, search for the line, find the most recent change, checkout that commit, search for the line, repeat.
> 
> I am having to rely a lot of git blame in order to see how / where the spec changes.

The `-S` and `-G` options to `git log` are remarkably useful. Sometimes `git bisect` will help me find what I'm looking for. And sometimes I do what you've described, if I think the target commit is only or or two 'blames' deep.

> So, I am wondering if other people share this issue and if we should tackle this somehow. For example, splitting spec.html into chapters that can be indexed by github, so we can track the history of changes through the file.

Are you hoping to get, for each line of the spec, a list of commits that have changed it? I'm not sure that's entirely possible, since the idea of "the same line, but changed" is easy for humans but difficult (in general) for software. It might be more plausible (though less useful) to annotate each *clause* with commits that have changed any line within it.

I think splitting the spec is pretty much orthogonal to the above.

**Comment by codehag** [comment]
I spoke with the searchfox folks, and they said it should be possible to make a render of the spec file. The bug is here: https://bugzilla.mozilla.org/show_bug.cgi?id=1639666

**Comment by codehag** [comment]
Rejoice! https://searchfox.org/ecma262/source/spec.html

(and over over the grey bar on the left. You can click through to previous diffs and examine the change over time)

**Comment by codehag** [comment]
my issue has been _resolved_.
