### ISSUE TITLE
Taking @@matchAll into account for isRegExp as well?

### ISSUE THREAD

**Issue by Huxpro** [tc39/ecma262#2073]
Op [isRegExp](https://tc39.es/ecma262/#sec-isregexp) treats any object with a property `@@match` as a RegExp-ish to allow some duck-typed extensionality, but not the new `@@matchAll`. This introduced "interesting" language features:

```js
// re w/o [Symbol.match] is treated as !isRegExp, so this should not throw.
var re = {
  [Symbol.matchAll]: function(str) { return str },
  flags: "blah"
}
print("abc cde".matchAll(re));  // abc cde

// re w/ [Symbol.match] is treated as isRegExp and now this throws!
var re = {
  [Symbol.match]: function(str) { return str },
  [Symbol.matchAll]: function(str) { return str },
  flags: "blah"
}
print("abc cde".matchAll(re));  // TypeError!
```

**Comment by ljharb** [comment]
This is very intentional; I consider it a mistake that `Symbol.match` doubles as "the match protocol" and "i am a regex" (see #1318) and I think it would have been a very bad idea to make the symbol for "the matchAll protocol" have a double meaning as well.

The "interesting" case you mention also applies to `Symbol.split`, `Symbol.search`, and `Symbol.replace`.

**Comment by Huxpro** [comment]
@ljharb Thanks for the info. It was an interesting read, especially the end of the story. 😂 
Does the committee still consider making `Symbol.match` not stayed as uniquely special? It's probably too much hassle to change the core-js and redo the use data collection though.

**Comment by ljharb** [comment]
I don't think there's a performant way browsers can *do* the data collection while ignoring core-js feature tests; if there were, and the data indicated it was web compatible, I'd happily attempt to change it again.

Closing, since this has been answered.
