### ISSUE TITLE
inconsistent notation for multiplication and division

### ISSUE THREAD

**Issue by michaelficarra** [tc39/ecma262#2183]
We inconsistently use `*` and &times; for multiplication and `/` and &divide; for division. We should use consistent notation.

**Comment by jmdyck** [comment]
The only place I see us using `*` for multiplication is in [MakeTime](https://tc39.es/ecma262/#sec-maketime), where it says "(that is, as if using the ECMAScript operators `*` and `+`)", so that's a conscious decision.

But yes re the inconsistency on division: we use `&divide;` twice (in [BigInt::leftShift](https://tc39.es/ecma262/#sec-numeric-types-bigint-leftShift) and [Number.prototype.toFixed](https://tc39.es/ecma262/#sec-number.prototype.tofixed)), and use `/` everywhere else.

**Comment by michaelficarra** [comment]
@jmdyck #2007 should be removing that first case soon.

**Comment by michaelficarra** [comment]
Discussed in the editor call today. Multiplication will use `×` and division will use `/`, in accordance with ISO 80000-2:2019.

@bakkot will double check that MakeTime uses the correct notation in #2007.

**Comment by bakkot** [comment]
Relevant bits of ISO 80000-2:

<img width="823" alt="Screen Shot 2020-09-30 at 3 26 10 PM" src="https://user-images.githubusercontent.com/1653598/94746303-4e7c9380-0331-11eb-8ed1-6471d33349c5.png">


<img width="817" alt="Screen Shot 2020-09-30 at 3 25 18 PM" src="https://user-images.githubusercontent.com/1653598/94746256-33aa1f00-0331-11eb-92eb-af3c91e24088.png">


<img width="819" alt="Screen Shot 2020-09-30 at 3 23 57 PM" src="https://user-images.githubusercontent.com/1653598/94746189-0cebe880-0331-11eb-81a0-a5b7043d8873.png">
