### ISSUE TITLE
Spec question about var & hoisting

### ISSUE THREAD

**Issue by Jack-Works** [tc39/ecma262#2308]
> eshost -x "var a = 10; {a=99; function a(){}; a = 30;} print(a)"

Is it expected?

```
#### ChakraCore
function a(){}

#### Hermes
30

#### Moddable XS
10

#### SpiderMonkey
99

#### V8
99
```

**Comment by bakkot** [comment]
Welcome to [Annex B.3.3](https://tc39.es/ecma262/#sec-block-level-function-declarations-web-legacy-compatibility-semantics), one of the [most horrifying parts of the specification](https://dev.to/rkirsling/tales-from-ecma-s-crypt-annex-b-3-3-56go).

SpiderMonkey and V8 are correct per the specification. XS chooses not to implement all of Annex B, which it is free to do since it is not a browser engine, and hence its behavior is also permitted. Hermes and ChakraCore are just wrong.

**Comment by Jack-Works** [comment]
thanks!
