### ISSUE TITLE
negative array index -0

### ISSUE THREAD

**Issue by djmisterjon** [tc39/ecma262#2309]
I wonder if the architecture of js could allow the support of negative value in the management of a array by index ?
Are these something JS might own in the future (natively in the vanilla engine)?
Have there already been discussions on this subject that would prevent the implementation of this approach?
```js
const path = "C:\folder\file.js";
const name = path.split('\\')[-0]; // log "file.js"
const folder = path.split('\\')[-1]; // log "folder"
```

**Comment by ljharb** [comment]
No, since `[-0]` already works to access index `0` in an array - for example, `[1][-0]`.

You may be interested in these language proposals:
 - https://github.com/tc39/proposal-relative-indexing-method (stage 3)
 - https://github.com/tc39/proposal-slice-notation (stage 1)
 - https://github.com/hax/proposal-index-from-end (stage 0)
