### ISSUE TITLE
Editorial: Potential mistakes in annexB scoping extensions

### ISSUE THREAD

**Issue by davidot** [tc39/ecma262#2540]
While implementing the annexB scoping extensions I noticed some of the names used/ordering seemed incorrect.

https://tc39.es/ecma262/#sec-web-compat-functiondeclarationinstantiation
B.3.2.1 Changes to FunctionDeclarationInstantiation
In step `29.a.ii.2` uses `initializedBindings` however this is not defined anywhere in `FunctionDeclarationInstantiation`  then appends to `instantiatedVarNames` in step `29.a.ii.2.c`.
Probaly both meant to both be `instantiatedVarNames`?

B.3.2.3 Changes to EvalDeclarationInstantiation
https://tc39.es/ecma262/#sec-web-compat-evaldeclarationinstantiation
In step `11.a` Uses a concatenation of `declaredFunctionNames` and `declaredVarNames` however `declaredVarNames` is only defined in step `12` of `EvalDeclarationInstantiation`.
Here either the extension should be after the current step `13` of `EvalDeclarationInstantiation`. Or `declaredVarNames` should not be used? But there could be more wrong here I have no idea.

I hope this issue is clear enough, otherwise let me know and I will try to expand on it.

**Comment by jmdyck** [comment]
> While implementing the annexB scoping extensions I noticed some of the names used/ordering seemed incorrect.
> 
> B.3.2.1 Changes to FunctionDeclarationInstantiation In step `29.a.ii.2` uses `initializedBindings` however this is not defined anywhere in `FunctionDeclarationInstantiation` then appends to `instantiatedVarNames` in step `29.a.ii.2.c`. Probaly both meant to both be `instantiatedVarNames`?

That step originally had `_instantiatedVarNames_`, but then it was changed (presumably unintentionally) to `_initializedBindings_` by https://github.com/tc39/ecma262/commit/ea167900a06af090a1158a17b5ee04c7bcafb015, which appears to be based on PR #891, which also has that change.

Issue #991 (still open) suggests changing it back. (See the last line of the first comment.)

**Comment by jmdyck** [comment]
> B.3.2.3 Changes to EvalDeclarationInstantiation https://tc39.es/ecma262/#sec-web-compat-evaldeclarationinstantiation In step `11.a` Uses a concatenation of `declaredFunctionNames` and `declaredVarNames` however `declaredVarNames` is only defined in step `12` of `EvalDeclarationInstantiation`. Here either the extension should be after the current step `13` of `EvalDeclarationInstantiation`. Or `declaredVarNames` should not be used? But there could be more wrong here I have no idea.

When the "Changes to EvalDeclarationInstantiation" section was introduced, it didn't reference `_declaredVarNames_`, so the placement of the 'insertion point' before the definition of `_declaredVarNames_` in EDI wasn't a problem. Commit https://github.com/tc39/ecma262/commit/6844342f1815db6de559a38c3abf52d74283fdfc (which appears to be based on PR #164) added the reference to `_declaredVarNames_` in the "Changes" section, but didn't move the insertion point, so that's when the problem arose.

(That commit has similar edits for GlobalDeclarationInstantiation, but those don't have the same problem, because the insertion point in GDI has always been after the definition of `_declaredVarNames_`.)
