### ISSUE TITLE
ArrayBuffer() & ArrayBuffer("some non-number") doesn't match implementations

### ISSUE THREAD

**Issue by bterlson** [tc39/ecma262#265]
@anba contributed [these](https://github.com/tc39/test262/blob/master/test/built-ins/ArrayBuffer/length-is-not-number.js) [tests](https://github.com/tc39/test262/blob/master/test/built-ins/ArrayBuffer/length-not-present.js) and highlighted an issue. See also this [v8 issue](https://bugs.chromium.org/p/v8/issues/detail?id=4592). No browser as far as I can tell implements the required ToNumber semantics. Considering we already have interoperable implementation here I doubt this will change. Seems like we should just do ToInteger rather than the ToNumber/ToLength incantation presently in [22.2.1.2](http://tc39.github.io/ecma262/#sec-%typedarray%-length). Thoughts?

**Comment by littledan** [comment]
Interestingly, as far as I can tell, ToLength was added exactly to support large TypedArrays. I think we should remain compatible with web usage and what implementations do, but I wonder if we can do it in a way which generally preserves some kind of consistency with ToLength.

As a strawman, what if we just replaced lines 3-6 with a simple ToLength call? That would handle coercing all sorts of things to 0, while guaranteeing that we're left with a positive integer. It would be a minor change vs current browser behavior, but as far as I can tell, it would only be in the direction of *not* throwing on negative numbers (where V8, for one, currently throws). An alternative would be

1. ToInteger
1. Check if it's < 0, if so throw
1. ToLength of that

which would leave us with that nice, higher level of checking, and verifying that the result is within (2**53)* range, while still allowing undefined etc to be coerced in a web-compatible way.

* To be unambiguous, I put parens around all exponentiation

**Comment by littledan** [comment]
Another place where this comes up is DataView setting/getting indices. Across all four browsers (at least for the last Safari release, and more recent versions of all other browsers), if I try to set something at the 'NaN' index, no exception is thrown. However, a new set of tests in the same patch by @anba highlighted that this violates the spec.

**Comment by zloirock** [comment]
Currently, [I use this inconsistency as an ultimative feature detection](https://github.com/zloirock/core-js/blob/master/modules/_typed-buffer.js#L243-L248) for wrapping `ArrayBuffer` for validation in the next version of  `core-js`, so, please, resolve this issue asap :)

**Comment by anba** [comment]
First of all I think it's hard to believe web-compatibility is affected when `new ArrayBuffer("I don't even know what I'm doing")` throws an error. It may even help to catch misuses like [this one](http://hg.mozilla.org/mozilla-central/file/c5cb194cc9cb/js/src/tests/ecma_6/DataView/detach-after-construction.js#l4) :stuck_out_tongue: .

But more importantly argument input validation should be consistent across ArrayBuffer, DataView and TypedArray, because all three are used together [0]. So if it gets decided that `new ArrayBuffer(1.4)` should not throw an error, we may also consider to remove the error when calling `new Int8Array(1.4)`. And IIRC input validation for these constructors has been discussed multiple times in the past, it's probably useful to check for es-discuss and meeting notes to find out why the validation steps were added in the first place.

Current situation for `ArrayBuffer(length)`:
Edge, JSC and SM use ToInt32/ToUint32 for `new ArrayBuffer(1.4)`, V8 calls ToInteger and performs [target platform](https://github.com/v8/v8/blob/d30693880c833e1d504e296aeca2260924cf6b1c/src/conversions-inl.h#L145) specific checks [1]. 

Current situation for `TypedArray(length)`:
JSC and SM only allow integer numbers ([here](https://github.com/WebKit/webkit/blob/a2de5f3a64699ab21d34570dcd72e7c9816b0010/Source/JavaScriptCore/runtime/JSGenericTypedArrayViewConstructorInlines.h#L202) and [here](https://github.com/mozilla/gecko-dev/blob/71603d10db578fb61cc5b1d881830f882dcfbda0/js/src/vm/TypedArrayObject.cpp#L459)), Edge only allows numbers and calls ToInt32, V8 calls ToInteger ([here](https://github.com/v8/v8/blob/53a0cc846661c65b4b1711f67642677d8da69119/src/js/typedarray.js#L149) [2]) and performs a range check for SMIs.



[0] It's already not quite consistent when you compare the length parameter checks in 22.2.1.2 and 22.2.1.5.
[1] I wonder if that check is actually valid for 64-bit when value is near size_t-max, e.g. `new ArrayBuffer(0x10000000000000000).byteLength` returns 0.
[2] And there is a missing check for symbol values in [this line](https://github.com/v8/v8/blob/53a0cc846661c65b4b1711f67642677d8da69119/src/js/typedarray.js#L211). `Symbol.prototype[Symbol.iterator] = function*(){ print("hi") }; new Int8Array(Symbol())` shouldn't print "hi" on the console. :wink:

**Comment by zloirock** [comment]
Ok. The first day of `core-js` 2.0 and looks like [the first problem with this inconsistency](https://github.com/karma-runner/karma/issues/1768#issuecomment-167193698) (`%TypedArray%` constructor, but with the same change).

**Comment by zloirock** [comment]
@anba 
> [2] And there is a missing check for symbol values

[Also, for example, `null`](https://bugs.chromium.org/p/v8/issues/detail?id=4552) `Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null`

**Comment by zloirock** [comment]
So... With this change for `%TypedArray%` constructor in Node.js in some cases will not work `ws` module -> `socket.io` -> dependent modules because passes to `Buffer` -> `Uint8Array` floats.

**Comment by domenic** [comment]
Do we consider this fixed with https://github.com/tc39/ecma262/issues/410 ?

**Comment by leobalter** [comment]
yes, this can be closed
