### ISSUE TITLE
Add support for arbitrary code inside template tags

### ISSUE THREAD

**Issue by manuel-di-iorio** [tc39/ecma262#279]
Why not support any arbitrary code inside template strings expressions?

This is not supported i.e:

    `${ if (a == 2) {
        console.log('hi');
    } }`

And with more complex code, like if, if-else, for loops, etc..

It would be nice to develop a template engine that uses this native approach instead of a string manipulation.

**Comment by michaelficarra** [comment]
Do-expressions will allow this:

```js
`${ do if (a == 2) {
    console.log('hi');
} }`
```

**Comment by manuel-di-iorio** [comment]
Awesome! Can I ask why the `do` keyword ?
Anyway, this is already good

**Comment by michaelficarra** [comment]
No, not at all. There's many things wrong with what you've written. `"Hello "` needs to be a literal part of the template, the completion value of the `if` statement is either `null` (the return value of `console.log`) or `undefined`, and in order to see the value produced by the template, it all needs to be within the argument list for `console.log`.

It seems you are very unfamiliar with JavaScript. I would recommend asking questions like this on Stack Overflow or some other medium. This issue tracker is meant for a different kind of discussion.

**Comment by domenic** [comment]
Per https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#feature-requests, closing this. @michaelficarra perhaps in the future redirect to StackOverflow sooner instead of indulging people :)

**Comment by manuel-di-iorio** [comment]
Sorry previously  I made a typo.. I meant:

    `Hello ${ do if (a == 2) {
        console.log(' world');
    } }`

@micheal nope I already asked on SO and they redirected me here..  However the issue is now closed and I'm happy with the feature proposal.  Hope to see its availability as soon as possible :)

**Comment by micheal** [comment]
I'm not the micheal you are looking for. :)
