### ISSUE TITLE
Please autodeploy the built spec

### ISSUE THREAD

**Issue by Ms2ger** [tc39/ecma262#296]
CC @bterlson @domenic

**Comment by mathiasbynens** [comment]
Travis CI could do this, using something like https://github.com/alrra/travis-scripts. See https://github.com/jakearchibald/isserviceworkerready/blob/206c54af0f8eb2b92f8affcc1abdd399c0a72a1d/.travis.yml#L5-L10 for an example.

**Comment by jakearchibald** [comment]
I use that on a few projects & it works great. Means I can even make changes using github's editor on my phone, and the changes get pushed live.

**Comment by domenic** [comment]
Yeah, I would really appreciate this too; the lag between commits and releases is not really helping anything.

**Comment by alrra** [comment]
> https://github.com/alrra/travis-scripts. 

I forked this project in order to show how things would work:

* some of the changes that would be required: https://github.com/alrra/ecma262/commit/fdb71c1341d38e52d8efea528a24d6db15c0680f  
 (Note: the [`favicon.ico`](https://github.com/tc39/ecma262/blob/d226c076305cddedd5eb4b6c4dccd61c9eb0049c/favicon.ico), [`figure-1.png`](https://github.com/tc39/ecma262/blob/d226c076305cddedd5eb4b6c4dccd61c9eb0049c/figure-1.png) & [`figure-2.png`](https://github.com/tc39/ecma262/blob/d226c076305cddedd5eb4b6c4dccd61c9eb0049c/figure-2.png) from the `gh-pages` branch need to be moved in `master`)
* how a [Travis build would work like](https://travis-ci.org/alrra/ecma262/builds/103395373#L254)
* the [end result](https://github.com/alrra/ecma262/tree/gh-pages) (see also http://alrra.github.io/ecma262/).

---

@bterlson, @domenic Let me know if your interested in something like that, and I can open a pull request. The only thing that you would need to do is enable Travis CI for this repository and generate your own secure key.

**Comment by bterlson** [comment]
@alrra I would be interested in something like this if you want to send a PR!

**Comment by alrra** [comment]
> if you want to send a PR!

@bterlson Done in #309.

**Comment by bterlson** [comment]
It is done.
