### ISSUE TITLE
Specify Date Time String with formal syntax and static semantics

### ISSUE THREAD

**Issue by Josh-Cena** [tc39/ecma262#2984]
The current [Date Time String Format](https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-date-time-string-format) section is written in a quite informal way, making it hard to understand what syntaxes are supported and which are required to result in `Invalid Date`.

For example, I cannot tell if the `YYYYTHH:mm` format is standard, because the optionality of each component is not indicated. The `YYYY-MM-DDTHH:mm` format is only mentioned once in an editorial note about `24:00` vs. `00:00`.

This also makes the notion of "invalid date" handwavy, because it's impossible to tell what constitutes "A string containing out-of-bounds or nonconforming elements". Can `20231` with five digits be matched by this grammar? Or `2022-12-19T11`? Is `2022-02-31` matched by the grammar, or is it simply rejected by "static semantics"? What about `2022-02-32`? (See also: https://github.com/tc39/ecma262/issues/197)

Is it possible to make `DateTimeString` a new grammar like `StringNumericLiteral`, especially considering that [Time Zone Offset String Format](https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-time-zone-offset-strings) is already, so that we know explicitly which formats necessarily result in `Invalid Date` and which may result in implementation-defined behavior?

**Comment by bakkot** [comment]
As far as I no there are no strings which are required to result in `Invalid Date` except those which match the specified format but have years outside the range of a valid date. For anything which doesn't match, implementations "may fall back to any implementation-specific heuristics or implementation-specific date formats". Unfortunately implementations differ wildly in those heuristics.

This can't be made more precise without figuring out what subset of `Date.parse` behavior is consistent across engines, because people absolutely do rely `Date.parse` with strings outside the minimal format currently specified. There are certainly some things in the intersection of major engines, but tracing out exactly what the boundaries are would be a bunch of work. There was a start to that effort [here](https://github.com/tc39/proposal-uniform-interchange-date-parsing) but it hasn't made progress in a while.

In practice I don't think anyone's going to be willing to put the effort in to figure out exactly what strings must be accepted, particularly now that Temporal is coming along with actually formal semantics.

**Comment by syg** [comment]
Choosing between putting my eggs in the Temporal bucket vs the "let's fix Date.parse" bucket, it's definitely going to be the Temporal bucket.

**Comment by Josh-Cena** [comment]
I'm mostly looking at the "match the specified format but have years outside the range of a valid date" yes. For example, if the month segment looks like:

```
Month :::
  0 DecimalDigit
  1 DecimalDigit
  2 DecimalDigit
  30
  31
```

Then `2022-02-32` is not matched by the grammar and may fall back to implementation-specific heuristics (specifically, wrapping). However, if it looks like:


```
Month :::
  DecimalDigit DecimalDigit
```

Then `2022-02-32` must be invalid. (Engines seem to wrap, indicating that "from 01 to 31" is indeed part of the grammar.)

---

I was assuming that people are going to freeze the `Date` section considering `Temporal` can become a thing at any time, but it's in a really awkward state and I'd argue `Date` is still a fairly simple model to work with, sans the weird date string format specification. Do editors believe that the current text is ambiguous, or is it possible to convert it to formal syntax without further field research about what's accepted and what's not?

**Comment by bakkot** [comment]
"2022-02-32" definitely does not have "expanded years representing instants in time outside the range of a time value", and so definitely is not _required_ to be invalid. Note that it is specifically only when _years_ are outside of range "invalid date" is required, not days or anything else.

> Do editors believe that the current text is ambiguous

Somewhat, yes.

> is it possible to convert it to formal syntax without further field research about what's accepted and what's not

No.

**Comment by Josh-Cena** [comment]
> Note that it is specifically only when _years_ are outside of range that "invalid date" is required, not days or anything else.

Interesting, because I can't interpret the spec that way.

> [21.4.3.2](https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-date.parse) The function first attempts to parse the String according to the format described in Date Time String Format ([21.4.1.18](https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-date-time-string-format)), including expanded years. If the String does not conform to that format the function may fall back to any implementation-specific heuristics or implementation-specific date formats. Strings that are unrecognizable or contain out-of-bounds format element values shall cause this function to return NaN.
> [21.4.1.18](https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-date-time-string-format) A string containing out-of-bounds or nonconforming elements is not a valid instance of this format.

21.4.1.18.1 does mention that

> Strings matching the [Date Time String Format](https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-date-time-string-format) with expanded years representing instants in time outside the range of a [time value](https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-time-values-and-time-range) are treated as unrecognizable by [Date.parse](https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-date.parse) and cause that function to return NaN without falling back to implementation-specific behaviour or heuristics.

But I was supposing this is a sufficient condition, not a necessary condition.

**Comment by Josh-Cena** [comment]
For context, I'm trying to address https://github.com/mdn/content/issues/21188 and I need to tell people where the boundaries of "explicitly specified syntax" are. It's possible I can get away with "don't use `Date`; just use `Temporal` instead", but unless TC39 takes the position that `Date` is a "legacy feature" through some spec markup or prose, I'm reluctant to do so.

**Comment by bakkot** [comment]
> But I was supposing this is a sufficient condition, not a necessary condition, particularly because it's a subclause.

It is a sufficient condition; that's what I said? I'm not clear on what you're disagreeing with.

To be precise:

- if it matches the format, then
  - if it has expanded years and they are out of range, it is `Invalid Date`
  - else, it's parsed as a date (precisely how is not completely specified)
- else, it's entirely up to implementations

So the only case where `Invalid Date` is required is when it matches the format and the years are out of range for a valid date. `Invalid Date` is permissible in other cases, but not required. Things which don't match the format may or may not result in `Invalid Date` at the discretion of the implementation.

In particular, this certainly does not say that `2022-02-32` is required to parse as `Invalid Date`, since it does not fall into the only branch which requires `Invalid Date`. That string falls into the "entirely up to implementations" branch, since `DD` is specified as "two decimal digits from 01 to 31", and "a string containing out-of-bounds or nonconforming elements is not a valid instance of this format". (It is less clear whether `2022-02-31` counts as "out of bounds".)

---

> For context, I'm trying to address mdn/content#21188 and I need to tell people where the boundaries of "explicitly specified syntax" are.

For documentation purposes, I think the formats listed in that section:

- the full `YYYY-MM-DDTHH:mm:ss.sssZ`
- the date-only `YYYY`, `YYYY-MM`, and `YYYY-MM-DD`
- the date-time things which consist of one of the date-only options followed by `THH:mm`, `THH:mm:ss`, or `THH:mm:ss.sss` with an optional UTC offset representation appended

are the only things you can reasonably call "explicitly specified". Do you think more guidance than that is needed for documentation?

**Comment by Josh-Cena** [comment]
Ah, that sounds reasonable. I misread and thought all "invalid instances of the format" need to be `NaN`, but in fact that just causes a parse failure and leads to fallback.

So to clarify: is `1995-02-04T24:00` part of the date time string format? It's mentioned in the editorial note but not explicitly included in the prose.

**Comment by bakkot** [comment]
> is `1995-02-04T24:00` part of the date time string format

Yes, and I think it's explicit in the prose, not just the note:

```
This format includes date-only forms:
[...]
- YYYY-MM-DD
[...]
It also includes “date-time” forms that consist of one of the above date-only forms immediately followed by one of the following time forms with an optional UTC offset representation appended:
- THH:mm
[...]
```
And all the individual components are in bounds (including `24` for `HH`). I don't think there's any ambiguity there. It's also explicit how to handle the lack of timezone offset: "When the UTC offset representation is absent [...] date-time forms are interpreted as a local time."

(I'm not saying this is necessarily _obvious_, but I do think it's explicit if you read carefully.)

**Comment by Josh-Cena** [comment]
Ah, apparently I wasn't reading carefully and missed the "one of the above date-only forms immediately followed by" part 😄

If there's no interest from the editors to rewrite this section, I think the current one is the best it can get.
