### ISSUE TITLE
The runtime semantics of <=

### ISSUE THREAD

**Issue by fangniyima** [tc39/ecma262#3022]
Description:
I'm learning this specification and when I read about the runtime semantics of <= I found the following problem (maybe I overlooked something).Below is the description:

![1](https://user-images.githubusercontent.com/76503086/222427031-b33b8a16-b00a-4154-9b9f-cff2b16591d6.png).

IsLessThan abstract method always seems to return undefined.Below is the description:

![2](https://user-images.githubusercontent.com/76503086/222427576-bf993ab1-e2fe-4b92-b75e-9b711cbb1b3b.png)

It seems to execute up to subsection 4.f.i.1.When one of the operands is NaN, undefined will be returned.
The last step in the runtime semantics of <=, which returns false when r is undefined.
This doesn't seem to work with the code results below:
```js
let obj1 = {}
let obj2 = {}
obj1 <= obj2    //true
```

**Comment by bathos** [comment]
Since you closed this, you probably figured it out already, but just in case: at 2.b and 2.c, `ToPrimitive(x|y)` evaluates to the string `"[object Object]"` and we’d exit at step 3.d with `true`. This happens despite the `number` hint because `%Object.prototype.valueOf%` doesn’t return a primitive. If prior code had replaced the `Object.prototype.valueOf` method or had defined an `Object.prototype[Symbol.toPrimitive]` method so that they returned `NaN`, the result would be false as you expected.

**Comment by fangniyima** [comment]
@bathos Thank you for your reply. I found my mistake and closed the problem
