### ISSUE TITLE
Default string coercion in sort (CompareArrayElements) leads to unintuitive results.

### ISSUE THREAD

**Issue by jcmalek** [tc39/ecma262#3050]
Steps 5 & 6 of 23.1.3.30.2 CompareArrayElements coerce values to strings by default when the sort comparison function is undefined:
`5. Let xString be ? ToString(x).`
`6. Let yString be ? ToString(y).`

This leads to the following unintuitive result when sorting numbers with the default sort:
`[1, 2, 3, 4, 5, 6, 7, 8, 9, 10].sort();`
which gives:
`[1, 10, 2, 3, 4, 5, 6, 7, 8, 9]`

And effectively walks users straight into all the associated bugs.

I personally believe the default sort should leave the types of the parameters alone and do the comparison directly on the original types.

I realize that this was likely not done originally in order to work around the problem of  having to compare 2 different type objects during the sort. Solutions to that original problem could include:
(1) Cast everything to a string (as was currently chosen).
(2) Throw an exception when 2 different types are compared.
(3) Give the types themselves an order (strings after numbers etc.)
(4) Other solutions?

Obviously, 2 & 3 are compatible with my expected behavior while the current situation of 1 is not.

In the short term, in order to avoid walking users into this problem, I would propose that the comparefn be made a required parameter and generate a warning if it is left undefined.

In the longer term, it could be good to debate and explore the other solutions to the original problem to come to a hopefully better default?

**Comment by bakkot** [comment]
Alas, it's absolutely not going to be possible to change this at this point, and warnings are outside the domain of the specification (and would be incredibly noisy besides). We might conceivably add other methods someday which could be used instead, and if you'd like to suggest new things rather than changing old things see [CONTRIBUTING.md](https://github.com/tc39/ecma262/blob/main/CONTRIBUTING.md), but this behavior will remain with us forever.

**Comment by jcmalek** [comment]
That is unfortunate :_(
