### ISSUE TITLE
MakePrivateReference and ResolvePrivateIdentifier assert that outer private environment can't be null

### ISSUE THREAD

**Issue by dSalieri** [tc39/ecma262#3080]
Let's take algorithm of getting **Reference Record** from [`MemberExpression.PrivateIdentifier`][member-expression] production.

To receive **Reference Record** from it spec says that we have to call [MakePrivateReference][makeprivatereference]. Well we go to the [MakePrivateReference][makeprivatereference] algorithm and what we see, we see in 2nd step assertation that **PrivateEnvironment** of **running execution context** can't be **null**. So this step suggest that we can't get here an error and also we can't get **null** from **PrivateEnvironment**.

What about the following example: 
```JavaScript
({}).#a; /// Uncaught Error: Cannot read private member #a from an object whose class did not declare it
```
If we run this code out of class method we'll get an error, but specification doesn't say about any errors.

---

And I almost forgot about [ResolvePrivateIdentifier][resolveprivateidentifier]. What if we have nested **PrivateEnvironments**?

```JavaScript
(new class {
  run(){
    console.log(this.#a);
  }
}).run(); /// Uncaught SyntaxError: Private field '#a' must be declared in an enclosing class
```

We know when we will invoke method of class we use **PrivateEnvironment** belong to our class. So what if private identifier won't be found in the class? Search must continue his job of searching. And here we go again [ResolvePrivateIdentifier][resolveprivateidentifier] says in the step 4th that outer private environment can't be **null**. It's equal to the first issue with [MakePrivateReference][makeprivatereference].

Why does spec make assertations instead of throwing errors? I suspect implementations should throw errors by themself before assertation.

P.S I'll be glad if I am mistake.

[member-expression]: https://tc39.es/ecma262/#prod-MemberExpression "Member Expression"
[makeprivatereference]: https://tc39.es/ecma262/#sec-makeprivatereference "MakePrivateReference"
[resolveprivateidentifier]: https://tc39.es/ecma262/#sec-resolve-private-identifier "ResolvePrivateIdentifier"

**Comment by bathos** [comment]
I believe the assertion is correct because of the [AllPrivateIdentifiersValid](https://tc39.es/ecma262/#sec-static-semantics-allprivateidentifiersvalid) static semantics rules, which would return false for that expression’s parse node outside of any class body where #a has been declared. The error thrown for `({}).#a` is a SyntaxError 

You might have been thrown off by the fact that Chrome/Edge’s REPL throws an `Error` for this instead of a SyntaxError. Try `eval(...)` to avoid getting these sorts of wonky behaviors that are specific to the way the REPL evaluates stuff; you’ll see that it’s really a SyntaxError (i.e. suggesting one should look for “Static semantics” + “Early errors” in the spec).

**Comment by dSalieri** [comment]
@batos thanks a lot, I had suspicion about early errors but didn't manage with it (searching in the wrong place).
