### ISSUE TITLE
Rename "to link" to "to load" in the Source Text Module Records section

### ISSUE THREAD

**Issue by sunkai9064** [tc39/ecma262#3141]
As stated in the title, changing "to link" to "to load" can better express the process：

> A Source Text Module Record is used to represent information about a module that was defined from ECMAScript source text (11) that was parsed using the goal symbol Module. Its fields contain digested information about the names that are imported by the module and its concrete methods use this digest to link, link, and evaluate the module.

Change to：

> A Source Text Module Record is used to represent information about a module that was defined from ECMAScript source text (11) that was parsed using the goal symbol Module. Its fields contain digested information about the names that are imported by the module and its concrete methods use this digest to load, link, and evaluate the module.

**Comment by jmdyck** [comment]
(Originally, it was "... to link, instantiate, and evaluate the module". Then PR #1312 changed several occurrences of "instantiate" to "link", and didn't notice what that did to this sentence.)

**Comment by sunkai9064** [comment]
@jmdyck Yes, I saw your answer in matrix, according to your reply, I changed "to link, link, and evaluate the module"  to "to load, link, and evaluate the module"

**Comment by jmdyck** [comment]
I suppose I should have clarified that I was saying that for the benefit of anyone who hadn't seen my reply in matrix.

**Comment by sunkai9064** [comment]
> I suppose I should have clarified that I was saying that for the benefit of anyone who hadn't seen my reply in matrix.

Sorry, I misunderstood your meaning. You should do this

**Comment by jmdyck** [comment]
Also, I realize there are organizations/repos where every PR has to fix at least one Issue, sometimes forcing you to create an Issue in order to file a PR. However, that's not the case here. The [CONTRIBUTING.md](https://github.com/tc39/ecma262/blob/main/CONTRIBUTING.md) file doesn't really go into this, but my impression is that, for editorial matters at least, creating an issue is appropriate when:
- you're wondering if something is a problem, or
- you're pretty sure it's a problem but have no idea how to fix it, or
- you've got a proposed solution but it's a lot of work, and you want to make sure the editors are on board before you do all that work.

But if you're pretty sure something is a problem, and you've got a proposed solution, and it's not a lot of work, it's fine to just submit a PR. That's been my experience anyway; the editors might have more to say on the topic.

(Again, that's for editorial matters. Normative changes are different, as they usually happen via the proposal process, not via unsolicited PRs.)

**Comment by sunkai9064** [comment]
> Also, I realize there are organizations/repos where every PR has to fix at least one Issue, sometimes forcing you to create an Issue in order to file a PR. However, that's not the case here. The [CONTRIBUTING.md](https://github.com/tc39/ecma262/blob/main/CONTRIBUTING.md) file doesn't really go into this, but my impression is that, for editorial matters at least, creating an issue is appropriate when:
> 
> * you're wondering if something is a problem, or
> * you're pretty sure it's a problem but have no idea how to fix it, or
> * you've got a proposed solution but it's a lot of work, and you want to make sure the editors are on board before you do all that work.
> 
> But if you're pretty sure something is a problem, and you've got a proposed solution, and it's not a lot of work, it's fine to just submit a PR. That's been my experience anyway; the editors might have more to say on the topic.
> 
> (Again, that's for editorial matters. Normative changes are different, as they usually happen via the proposal process, not via unsolicited PRs.)

Thanks for the reminder, and noticed that you corrected the title in the associated PR. I will pay attention to these details in the future.
