### ISSUE TITLE
Boolean interpretation to and from string

### ISSUE THREAD

**Issue by digimbyte** [tc39/ecma262#3216]
**Description:** Handling Serialized Boolean and parsing it through Boolean() is not consistent resulting in false positives

in its simplest form:
```js
console.log(Boolean('')); // Outputs: false
console.log(Boolean(Boolean('').toString())); // Outputs: true
```
I propose Boolean string input to interpret "false" => false  && "0" => false
would also improve serialization and deserialization if it was case insensitive 

many users have to create a custom function:
```js
function proBool(value:string|number) {
    if (typeof value === "string" && (value.toLowerCase() === "false" || value === "0")) {
      return false;
    }
    if (typeof value === "number" && value === 0) {
      return false;
    }
    return Boolean(value);
  }
```

**I do not know how to use the tools mentioned, I want to put my peace forward**

**Comment by nicolo-ribaudo** [comment]
While this could make sense when designing a language from scratch, JavaScript has had this behavior for more than 25 years and changing it now would be a huge breaking change. The current behavior also follows the precedent set by many other languages, such as C.

I also had to write a function similar to your `proBool` sometimes (example: https://github.com/babel/babel/blob/cc4f1785c52faaba728640a0ce4be1450ed557e1/babel.config.js#L362-L364), but unfortunately changing the `Boolean` behavior is not feasible.

This _could_ be pursued as a proposal to add a new `Boolean.fromString` function, but such a proposal would first need to show that it's common to have to perform those conversions in multiple places. If you want to pursue this path, please read https://github.com/tc39/ecma262/blob/main/CONTRIBUTING.md#new-feature-proposals. Please note that new features have a very high bar to convince some delegates that they are worth spending time exploring.

In my personal experience, I have only have to do it when dealing with env variables and not in general: and it would be enough to "fix" this in the mechanisms that platforms use to expose those values, rather than as a core language feature.

**Comment by digimbyte** [comment]
so your saying its an oversight that has existed for 25 years and no one bothered to fix it sooner?
seems like something that should be considered moving forward. possibly survey how others have done it, I am 99% confident, all users have created an intermediate function because the core issue is handling serialized data.

I see the issue with making a breaking change, a fromString() is an excellent compromise.
However, this might be ideal for a major update in the future. I just don't want to have Boolean's flaws outlive the human race.

**Comment by bakkot** [comment]
There's not going to be a major update of that kind. Boolean's flaws will outlive the human race.
