### ISSUE TITLE
[Suggestion] Removal or replacement of functions used to introduce security vulnerabilities in modern web applications

### ISSUE THREAD

**Issue by DavidFernee** [tc39/ecma262#3338]
Dear tc39 community,

I write with a suggestion regarding the use of ECMA/JavaScript in modern web applications to introduce software security vulnerabilities. Could you please look at the functions used to introduce these vulnerabilities, replace them with functions that cannot be used for that purpose, and remove those functions that can be used for that purpose from future versions of the standard?

Perhaps this could be done with a view to making it extremely difficult or almost impossible to introduce a security vulnerability in an application using ECMA/JavaScript, even for an amateur?

Kind regards,

David

**Comment by ctcpip** [comment]
what did you have in mind?

**Comment by DavidFernee** [comment]
Examining the common security vulnerabilities that have been introduced and exploited by ECMA/JavaScript functions over the years and reengineering so that it would be almost impossible for any programmer to do so again.

**Comment by ctcpip** [comment]
Can you provide one example of a built-in JavaScript function you are referring to?

**Comment by DavidFernee** [comment]
I am no expert and it’s certainly not my area, but I am more than happy to embarrass myself by making some suggestions. Programmers in secure coding courses are taught to avoid functions that evaluate strings as code (e.g. eval, Function, setTimeout, and setInterval), could this be reevaluated at the language level?

Could you deny access to cookies via document.cookie by default?

Could Object.prototype be frozen by default?

Where sql injection vulnerabilities are introduced, could the function be replaced with others that query without the use of sql statements directly in code? That way user inputs could not execute on the database… Or if you want to query a database directly with a string, you have to disable a protection (or several) of the language.

Things of that nature. I’m not sure what is practical and what isn’t. Essentially a secure by default mindset. So you have to disable native protections to introduce vulnerabilities at all.

**Comment by Jack-Works** [comment]
I believe it is the `Object.prototype.__proto__` getter/setter. There isn't much thing we can do in the language. For `eval` and `Function` we have `trustedTypes` (on Web).

**Comment by ctcpip** [comment]
Please note that several of the things you mentioned are not part of JavaScript:  `setTimeout`, `setInterval`, `cookie` are part of the HTML standard. Protecting against injection attacks are also outside the scope of what can be done in the language itself.  Of course, that doesn't mean that committee members aren't interested in solving security issues outside the scope of the language, but they can't be addressed in ECMA-262.

The committee is actively working on the problem space you are referring to.

You might be interested in things like:

- [eval() and new Function: changes for Trusted Types](https://docs.google.com/presentation/d/14AjvbW2-aNvlirB-7pPhIAeM7oWKtjqONRcyp9ID7gg/edit#slide=id.p)
- [ShadowRealm](https://github.com/tc39/proposal-shadowrealm)
- [Secure ECMAScript](https://github.com/tc39/proposal-ses)
- [Compartments](https://github.com/tc39/proposal-compartments)
- ... and much more!

It is not possible at the language level to prevent the introduction of all possible security vulnerabilities, and the overwhelming majority of vulnerabilities are not fixed by changing something in the language. Responsibility for preventing security vulnerabilities will always fall to developers.

[TC39-TG3: Security](https://github.com/tc39/tg3) is a better space for discussing security concerns, particularly in the absence of a concrete suggestion for a specific change to the language.

**Comment by DavidFernee** [comment]
Do forgive me, but that’s what you get when you ask someone that is unfamiliar with a language to make language specific suggestions.

I did not ask you or even imply that it was practical or possible to remove the potential for all security vulnerabilities. “Perhaps this could be done with a view to making it extremely difficult or almost impossible to introduce a security vulnerability in an application using ECMA/JavaScript…” was the phrase I used.

I disagree with the rhetoric you use that, “…and the overwhelming majority of vulnerabilities are not fixed by changing something in the language…” I suspect they could be… If you want someone else to do the work and propose exhaustive changes to things that those working on the standard should already know very well how to fix, then perhaps you should say that you are simply lazy or underfunded for such a thing?

The other statement you make, “Responsibility for preventing security vulnerabilities will always fall to developers[,]” is a statement I fundamentally disagree with. A lot more can be done at the language level and, in my humble opinion, you are simply passing the buck and making excuses for something you should be taking more responsibility over.

Quite frankly this was the reaction I expected so I cannot say I am surprised.

**Comment by ljharb** [comment]
@DavidFernee your initial issue contained a request:
> Could you please look at the functions used to introduce these vulnerabilities, replace them with functions that cannot be used for that purpose, and remove those functions that can be used for that purpose from future versions of the standard?
>
> Perhaps this could be done with a view to making it extremely difficult or almost impossible to introduce a security vulnerability in an application using ECMA/JavaScript, even for an amateur?

We have already been doing these things in various forms for decades, and with the recently created TG3 group, are looking at them even more rigorously.

If you have concrete suggestions, we'd love to hear them, but this current vague suggestion of "make things more secure" isn't new information :-)

**Comment by DavidFernee** [comment]
Then why do we have the same classes of vulnerabilities being introduced constantly? Why is the problem getting worse and not better? Would you like me to ask a few of the universities here if they will put a few PhD students on the problem and give you the specific suggestions you require? I am looking for new thinking here, not simply “make things more secure[,]” but make it so difficult to introduce a vulnerability at the language level, that it is next to impossible for the developer to make a mistake.

**Comment by ljharb** [comment]
Because computers are hard?

Thanks for your suggestion, but “why don’t you just not make bugs?” simply isn’t a helpful suggestion.

If you can locate someone who is familiar with the language and has concrete suggestions, we’d love to hear them! In general, i don’t think there’s many contexts where uninformed abstract suggestions are particularly well received, unfortunately.

**Comment by ctcpip** [comment]
@DavidFernee Please understand that we are actively working on these issues both within and outside TC39. Specifically regarding your post, which suggests replacing and removing functions from the language, this is unlikely due to a crucial principle of web standards bodies: "Don't break the web." Changing a function to eliminate a possible attack vector is almost certain to disrupt valid, non-malicious use cases as well. This constraint often prevents us from making the changes we would like.

**Comment by DavidFernee** [comment]
If you think computers are hard, I suggest you find a different profession and stop making excuses for your failures.

All I read is a closed-minded thinking. Could you specify a validation within the specification for user input, so that it could only ever be treated as user input and not as code? If you don’t want to do that, could you force validation and handling of user input within the specification? 

Do I have to ask the browsers to implement a static JavaScript analysis feature and not render code that improperly handles user input and posts a big red insecure banner instead?

You say I might break the internet, I say because of people like you the internet is fundamentally broken and in need of fixing.

I can send off emails to academic institutions today to request that some PhD students look at the language with a view to removing even the possibility of injection vulnerabilities from ECMAScript altogether. Would you like me to do that, or are you utterly hellbent on people being able to hack poorly written web applications with ECMAScript?

**Comment by ljharb** [comment]
ECMAscript has no injection vulnerabilities except for Function and eval - you may be thinking of the web, which has a lot, as well as a lot of experts already spending a lot of years developing a lot of approaches to solve that very class of problem.

Please do request concrete suggestions; I’m not sure how you can expect us to act on anything else.

**Comment by ctcpip** [comment]
> Could you specify a validation within the specification for user input, so that it could only ever be treated as user input and not as code? If you don’t want to do that, could you force validation and handling of user input within the specification?

No, we could do neither.  User input is outside the scope of the language.  We have no way of knowing at the language level whether values passed to functions come from user input or not.

User input on the web is handled by [DOM and other web APIs](https://developer.mozilla.org/en-US/docs/Web/API#specifications) generally defined in the HTML standard, for which [WHATWG](https://whatwg.org/) is responsible.

> I can send off emails to academic institutions today to request that some PhD students look at the language... Would you like me to do that

Sure!  Academics make up an important part of the committee and we would be very happy to have more join us.

Please be mindful of our [Code of Conduct](https://tc39.es/code-of-conduct/).

**Comment by DavidFernee** [comment]
So in your opinion ECMAScript does not have any facility to accept user input from any source?

**Comment by DavidFernee** [comment]
Good thing you don’t work for me, with an attitude like that, I would fire your entire committee for incompetence.

“User input is outside the scope of the language[,]” is the most ridiculous statement I have ever heard in my life.

**Comment by ctcpip** [comment]
> ECMAScript does not have any facility to accept user input from any source?

Not directly, no.  It is only possible through the use of intermediary APIs such as `DOM` on the web, or `readline`/`process.stdin` in node.

**Comment by ctcpip** [comment]
> ECMAScript does not have any facility to accept user input from any source?

Not directly, no.  It is only possible through the use of intermediary APIs such as `DOM` on the web, or `readline`/`process.stdin` in node. And when those values are read and then passed to built-in JavaScript methods, we have no way of knowing at the language level whether that those values came from user input.
