### ISSUE TITLE
Console log before array destructuring triggers error

### ISSUE THREAD

**Issue by Tolu-Mals** [tc39/ecma262#3386]
I noticed that when you log an array to the console right before swapping some of its values using array destructuring, the following error is always thrown:

![Screenshot 2024-08-10 at 1 54 25 PM](https://github.com/user-attachments/assets/418312f5-99f8-473b-9fe3-01053dc98a52)

I was able to reproduce this behaviour on 

-  Browser environment Replit 
- Nodejs environment on Leetcode
- Nodejs environment on Replit

I used this code to reproduce the error

```js
let arr = [1, 2, 3, 4, 5]

console.log("arr: ", arr)
[arr[0], arr[1]] = [arr[1], arr[0]]
```
[Replit reproduction](https://replit.com/@Tolu-Mals/SwapWithDestructuring)

**Comment by bergus** [comment]
https://web.archive.org/web/20201206065632/http://inimino.org/~inimino/blog/javascript_semicolons

**Comment by jmdyck** [comment]
In more detail:
Because you omitted the semicolon after `console.log(...)`, your script is parsed the same as if you had said:
```
console.log("arr: ", arr)[arr[0], arr[1]] = [arr[1], arr[0]]
```
but `console.log(...)` returns undefined, so this is equivalent to
```
undefined[1, 2] = [2, 1]
```
which throws a TypeError because you're trying to treat undefined like an array. (I think.)

The bottom line is that the effects of automatic semicolon insertion (ASI) can be unintuitive, so be careful (or avoid it).

**Comment by Tolu-Mals** [comment]
> ur script is parsed the same as if you had said:

Really helpful, thank you
