### ISSUE TITLE
Behavior of for-in on null or undefined

### ISSUE THREAD

**Issue by GeorgNeis** [tc39/ecma262#377]
What should happen when trying to enumerate (for-in) null or undefined?  If I understand the spec correctly, currently such a for-in statement is equivalent to a break, which I find very strange:

http://tc39.github.io/ecma262/#sec-runtime-semantics-forin-div-ofheadevaluation-tdznames-expr-iterationkind

```
6. If iterationKind is enumerate, then
  a. If exprValue.[[value]] is null or undefined, then
    i. Return Completion{[[type]]: break, [[value]]: empty, [[target]]: empty}.
```

(I would have expected that this returns a normal completion record with the undefined value.)

**Comment by GeorgNeis** [comment]
Why is this If there at all? Letting ToObject (which is called next) throw a TypeError seems reasonable.

**Comment by bterlson** [comment]
It does eventually return an undefined value with a normal completion. The break completion value is handled uniformly in [13.1.7](https://tc39.github.io/ecma262/#sec-statement-semantics-runtime-semantics-labelledevaluation). I'm not sure if the break semantics are required for some reason but it does just work with the existing machinery so that's a plus. You could imagine (I think) checking the result of evaluating the head in each block of 13.7.5.11, though I'm not inclined to change this without good reason.

**Comment by GeorgNeis** [comment]
Thank you, I missed that.
