### ISSUE TITLE
TypedArray ArrayBuffer constructor allowing negative length?

### ISSUE THREAD

**Issue by littledan** [tc39/ecma262#468]
Was this intended? In https://tc39.github.io/ecma262/#sec-typedarray-buffer-byteoffset-length , a number of the arguments are checked to be greater than or equal to 0, but the length simply has ToLength applied to it, without this check. V8 currently checks that the argument is >= 0. Unlike other places where the ES2017 draft specification asks us to be more strict than we currently are, this asks us to be more lenient. I'd be fine to implement it, but before weakening the restrictions and releasing this to the web, I have to ask, was this intentional? When it is web-compatible, I like the idea of making/keeping interfaces strict in their input validation. The negative length is checked to be possible by the test262 test `built-ins/TypedArrays/buffer-arg-defined-negative-length` @allenwb

**Comment by domenic** [comment]
I don't have any specific input on this issue but I wanted to share a strategy that we often use for similar things to the typed array situation, where we're investigating how well a new-ish spec matches a long legacy of not-so-robust implementations. What we do is construct a quick test case in jsbin or live dom viewer, then create a Markdown table and fill in what we can with the test results and ask others to fill on cells for browsers we don't have on our computer (like Safari or Edge).

You can see some examples at https://github.com/whatwg/html/issues/823#issuecomment-193236577 and https://github.com/whatwg/html/issues/775#issuecomment-190796607.

This might be helpful for finding out if V8's check is a minority among browsers and the spec matches the others, or if all browsers agree and the spec mismatches reality, or what.

**Comment by allenwb** [comment]
This appears to be a bug, that took  a couple to steps to introduce.

Prior to [ES6 Rev17](http://wiki.ecmascript.org/lib/exe/fetch.php?id=harmony%3Aolder_es6_drafts&cache=cache&media=harmony:working_draft_ecma-262_edition_6_08-23-13-rev17markup.pdf) ToNumber rather than ToLength was applied to the *length* argument and a **RangeError** was thrown if the result number was < 0.  See 15.13.6.1.4 of Rev 17.

[Bug 2171](https://bugs.ecmascript.org/show_bug.cgi?id=2171) pointed out that the test was unnecessary because ToLength never returns a value < 0.  So the check was deleted in [Rev 21](http://wiki.ecmascript.org/lib/exe/fetch.php?id=harmony%3Aspecification_drafts&cache=cache&media=harmony:working_draft_ecma-262_edition_6_11-08-13.pdf) 22.2.1.4

The original bug was the simple replacement of the ToNumber with the ToLength.  The *length* argument should probably be handled similarly to what is currently done in [22.2.4.2](https://tc39.github.io/ecma262/#sec-typedarray-length)

**Comment by littledan** [comment]
@allenwb Based on the rest of the TypedArray specification, that sounds entirely reasonable. However, I'm still not sure about the web compatibility of the general strategy of throwing an exception on non-integer arguments to various TypedArray/DataView/ArrayBuffer-related functions, which is under discussion at #265 . (I believe @zloirock has found some compatibility issues when he tried to ship these semantics in core.js.) For now, I'll hold off on allowing negative lengths in V8, and I'd be in favor of the spec change that @allenwb is suggesting.

**Comment by littledan** [comment]
The compat issue: https://github.com/karma-runner/karma/issues/1768

@leobalter Would you be interested in writing up the spec fix that @allenwb is suggesting?

**Comment by leobalter** [comment]
Sure, I'll check it tomorrow.

**Comment by bakkot** [comment]
I believe this is fixed after #410: `length` is now passed through `ToIndex`, which throws on negative inputs.
