### ISSUE TITLE
Inconsistencies in semantics of default module exports.

### ISSUE THREAD

**Issue by GeorgNeis** [tc39/ecma262#586]
In [15.2.3.11](https://tc39.github.io/ecma262/#sec-exports-runtime-semantics-evaluation) (Runtime Semantics: Evaluation), the evaluation of default exports
sets the exported object's "name" property to "default" in some cases. Unless I'm
misreading something, this is done in an inconsistent way.

This will set the class's .name to "default":
`export default class {}  // ClassDeclaration`
This won't:
`export default (class {});  // AssignmentExpression`

For functions, the situtation seems reversed:

This will set the function's .name to "default":
`export default (function() {});  // AssignmentExpression`

This won't:
`export default function() {}  // HoistableDeclaration`

Is this intended?

**Comment by allenwb** [comment]
>This won't:
>```
export default (class {}); // AssignmentExpression
```

It will.  This form is handled by the  *ExportDeclaration* : **export default** *AssignmentExpression* **;** algorithm in [15.2.3.11](https://tc39.github.io/ecma262/#sec-exports-runtime-semantics-evaluation). Because IsAnonymousFunctionDefinition will return true for an **AssignmentExression** that is an anonymous class declaration.

>This won't:
>```export default function() {} // HoistableDeclaration
```

This looks like a spec. bug to me. The HoistableDeclaration case looks like it should have a step similar to step 4 of the ClassDelaration case of [15.2.3.11](https://tc39.github.io/ecma262/#sec-exports-runtime-semantics-evaluation). 

I can't recall any reason why I would have intentionally left it out for the HoistableDeclaration case.

**Comment by GeorgNeis** [comment]
Thanks for pointing out my misunderstanding regarding the first part.  Regarding the second part, maybe I'm wrong as well: I just found InstantiateFunctionObject, which is called in 15.2.1.16.4 (ModuleDeclarationInstantiation) and sets the "name" property to "default".

**Comment by GeorgNeis** [comment]
I guess this can be closed. I no longer think there is a bug.
