### ISSUE TITLE
`Reflect.construct`: "is not present" → "is not undefined"?

### ISSUE THREAD

**Issue by ljharb** [tc39/ecma262#647]
https://tc39.github.io/ecma262/#sec-reflect.construct step 2.

In general it seems like we've tried to change "presence" to "isn't undefined" in the spec. Is this an oversight, or intentional?

**Comment by jmdyck** [comment]
> In general it seems like we've tried to change "presence" to "isn't undefined" in the spec.

It does? In the current spec, I count 64 occurrences of "is present" and 57 of "is not present" (plus 6 of "is absent"). Those are quite close to the counts for ES6, and way more than the counts for ES5.

The count for "undefined" is up by about 4% since ES6, but offhand, it doesn't look like much (if any) of the increase is in places where "is [not] present" might otherwise have been used.

(Note that this isn't arguing against the merits of the proposed change, just against the notion that it's a general trend.)

**Comment by claudepache** [comment]
Here is an argument for the current semantics "is absent".

Let’s say I write

```js
function Bar() {
    // ....
    const obj = Reflect.construct(Foo, args, new.target)
    // ...
    return obj
}
```

assuming that `new.target` is an object. Now suppose that it happens once that `new.target` is undefined (because a consumer forgot to write `new`). With the current semantics, I get a TypeError, which is fine. With the semantics "defaults to the first argument", there is a good chance that I get an unwanted result.

Another argument is consistency with Reflect.get and Reflect.set.

**Comment by claudepache** [comment]
> It does? In the current spec, I count 64 occurrences of "is present" and 57 of "is not present" (plus 6 of "is absent"). Those are quite close to the counts for ES6, and way more than the counts for ES5.

@jmdyck Your counting is flawed. If you look closely, you'll see that only 4 of the 57 occurrences of "is present" has to do with a supplied argument to a function of the standard library. On the other hand, you missed "is supplied" (Date.UTC), "number of actual arguments" (String.prototype.splice), etc.

**Comment by jmdyck** [comment]
> only 4 of the 57 occurrences of "is present" has to do with a supplied argument to a function of the standard library

The original post didn't make that restriction, so I didn't either.

**Comment by bterlson** [comment]
There is a distinction for built-in functions between "is not present" and "is present but undefined" that I don't think we want to remove at this time.
