### ISSUE TITLE
CreateDataProperty is sometimes called with ? but can't throw

### ISSUE THREAD

**Issue by jyasskin** [tc39/ecma262#703]
https://tc39.github.io/ecma262/#sec-internalizejsonproperty, https://tc39.github.io/ecma262/#sec-createdatapropertyorthrow, and a few other places use "? CreateDataProperty(...)", but its definition appears to use just `true` and `false` return values to say whether it has succeeded.

This is related to #253.

**Comment by shvaikalesh** [comment]
`O` may be an exotic Proxy object with `defineProperty` trap that throws.

**Comment by jyasskin** [comment]
In that case, the far more common use of CreateDataProperty() without either ! or ? should be fixed.

**Comment by shvaikalesh** [comment]
I have checked all (49) usages of `CreateDataProperty` without `!` or `?` and did not find any calls that may receive Proxy as first argument.

**Comment by ljharb** [comment]
@shvaikalesh any user-provided object, including "this" values, could be a Proxy.

**Comment by shvaikalesh** [comment]
All `!` / `?`-less calls operate on objects created in the same abstract operation or method, mostly arrays or plain object, sometimes `arguments` exotic. They do not get any user-passed stuff.

**Comment by shvaikalesh** [comment]
> may receive Proxy as first argument.

sorry for the confusion, I meant first argument of `CreateDataProperty`

**Comment by ljharb** [comment]
Does the HTML spec use that abstract operation at all?

**Comment by annevk** [comment]
@ljharb it does at the end of https://html.spec.whatwg.org/multipage/infrastructure.html#structuredclone preceded by `?`. Although I think in HTML's case it cannot really be called on a proxy so maybe that is wrong?

**Comment by ljharb** [comment]
There are currently 4 remaining uses of `?` with `CreateDataProperty` in the spec:
 - 1 in `CreateDataPropertyOrThrow` (this is fine)
 - 2 in `InternalizeJSONProperty`, which are intentional and noted as such explicitly
 - 1 in `OrdinarySetWithOwnDescriptor`

Since `[[DefineOwnProperty]]` could throw, the `?` on `CreateDataProperty` seems correct to me - but I could easily be wrong here. As I see it, this issue should be closed with one of two outcomes:
 1. Removal of the `?` on the `[[DefineOwnProperty]]` call inside `CreateDataProperty`, with an accompanying assertion that `O` must be an ordinary object (or whatever assertion is applicable to ensure it can't throw), and then removal of the `?` on all `CreateDataProperty` calls
 1. No further change is needed.

I'm going to close it assuming the latter; but will happily reopen it if needed.

**Comment by annevk** [comment]
HTML seems to have changed to use `!` meanwhile, FWIW.
