### ISSUE TITLE
IDL needs hook for subset of OrdinarySet

### ISSUE THREAD

**Issue by annevk** [tc39/ecma262#719]
For https://github.com/heycam/webidl/issues/201 we need a way to invoke step 3-onward of OrdinarySet.

Would something like OrdinarySetWithOwnDesc(O, P, V, Reciever, ownDesc) be okay? Should this new abstract operation be a subsection or sibling section of OrdinarySet?

**Comment by Ms2ger** [comment]
So like https://github.com/tc39/ecma262/issues/566?

**Comment by domenic** [comment]
Welp. Um, I guess I've reversed my position since #566, and think that we should indeed factor it out.

The alternative would be to add a giant warning in the ES source code like `<!-- FILE AN ISSUE ON WEB IDL BEFORE CHANGING THIS IN ANY WAY -->`, but I think a refactoring would probably be clearer.
