### ISSUE TITLE
Why function.name is not well known symbol?

### ISSUE THREAD

**Issue by laland** [tc39/ecma262#742]

**Comment by UltCombo** [comment]
Do you mean `Function.prototype.name` or `(function() {}).name`? In any case, it is not a symbol, it is just a property.

**Comment by laland** [comment]
I mean  ```Function.prototype.name```, i know that it's not a symbol. But "name" is a such common concept for classes (that are functions in ES). Lots of classes have a "name" property to represent the names of the things, like ```class Hotel``` will have a ```name``` property to store hotel name, ```class Brand``` will have ```name``` to represent brand name, and so on... By defining ```name``` property in my class i`ll lose ability to get class name with ```Function.prototype.name```. ES has the concept of "well known symbols", like ```@@iterator``` or ```@@toPrimitive```, which purpose was to have some internal properties that can't be accidentally overriden by user. But we still have the ```Function.prototype.name```. Why it's not a ```@@name``` or ```__name__```?

**Comment by michaelficarra** [comment]
This conversation should be moved to es-discuss. Please see [the `CONTRIBUTING.md` document](https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md).

**Comment by UltCombo** [comment]
Oh, I see. If it is a feature request for a new symbol, then it should be moved to ES Discuss as Michael commented.

ECMAScript must have strong backwards compatibility in order to not break the web, and the `name` property has been there since forever. Classes also have been designed to be mostly compatible with the existing constructor patterns and avoid refactoring hazards.

So the `name` property cannot be removed and there's no strong motivation to add a symbol for that so far.

> By defining name property in my class i`ll lose ability to get class name with Function.prototype.name.

What exactly do you mean? Assigning a `name` to the instance will not affect the class/constructor name:

```js
class C {
  constructor() {
    this.name = "instance name";
  }
}

console.log(C.name); // "C"

const c = new C();
console.log(c.name); // "instance name"
console.log(c.constructor.name); // "C"
```

**Comment by laland** [comment]
Oh, looks like i missed that x_x Thanks for explanation )
