### ISSUE TITLE
Date comparsion bug

### ISSUE THREAD

**Issue by vadimzham** [tc39/ecma262#896]
```js
a = new Date();
b = new Date(); 

a == b;  //false
a < b;  //false
a <= b;  //true  
```
This must be very strange mechanics.

**Comment by claudepache** [comment]
This is correct.
* `a == b` is false, because `a` and `b` are not the same Date _object_. It does not test whether they represent the same moment.
* On the other side, relational operators like `<` convert their operand to primitives before comparison. The primitive value of a Date object is the number of milliseconds since the epoch; so that they compare correctly the moments they represent.

The root issue is that `==` has different meanings according to the type of its operands (compares references for objects, compares values for primitives). This is unfixable. Use something more explicit than `==`, e.g. `a.valueOf() == b.valueOf()`.
