### ISSUE TITLE
Division and rational numbers

### ISSUE THREAD

**Issue by cxielarko** [tc39/ecma262#901]
Are Integers intended to be compatible with a (hypothetical) rational type, and if so, how should division be handled? Under the current definition of division, either integers couldn't be treated as a subset of rationals, or there would need to be a separate operator for rational division.

**Comment by littledan** [comment]
Under this proposal, division of integers always results in an Integer (or an exception for dividing by zero), based on round-towards-zero semantics. If we add a rational type later, the way to get at rational division would be to cast both arguments to a rational, and then divide.

It's understandable if this behavior and future interface is undesirable. One alternative here would be to throw in this proposal on all division, so that we can make it result in another type to express the exact answer in a future proposal. However, this choice would be an unfortunate missing feature as far as ergonomics, and it would block users who would use Integer to get at many machines' underlying int64 division hardware.

**Comment by ljharb** [comment]
This question belongs in the [proposal repo](https://github.com/tc39/proposal-integer) itself, not here on the spec repo.
